DOMAIN = "animal_health"
NAME = "Animal Health"
DATABASE_NAME = "animal_health.db"
DATABASE_SCHEMA_VERSION = 2

ANIMAL_STATUS_ACTIVE = "active"
ANIMAL_STATUS_MISSING = "missing"
ANIMAL_STATUS_SOLD = "sold"
ANIMAL_STATUS_REHOMED = "rehomed"
ANIMAL_STATUS_DECEASED = "deceased"
ANIMAL_STATUS_OTHER_DEPARTURE = "other_departure"
ANIMAL_STATUSES = (
    ANIMAL_STATUS_ACTIVE,
    ANIMAL_STATUS_MISSING,
    ANIMAL_STATUS_SOLD,
    ANIMAL_STATUS_REHOMED,
    ANIMAL_STATUS_DECEASED,
    ANIMAL_STATUS_OTHER_DEPARTURE,
)

ANIMAL_SEX_MALE = "male"
ANIMAL_SEX_FEMALE = "female"
ANIMAL_SEX_OTHER = "other"
ANIMAL_SEXES = (
    ANIMAL_SEX_MALE,
    ANIMAL_SEX_FEMALE,
    ANIMAL_SEX_OTHER,
)

SERVICE_CREATE_ANIMAL = "create_animal"
SERVICE_UPDATE_ANIMAL = "update_animal"
SERVICE_SET_ANIMAL_STATUS = "set_animal_status"
SERVICE_ARCHIVE_ANIMAL = "archive_animal"
SERVICE_RESTORE_ANIMAL = "restore_animal"

ATTR_DEVICE_ID = "device_id"
ATTR_ANIMAL_ID = "animal_id"
ATTR_NAME = "name"
ATTR_SPECIES = "species"
ATTR_BREED = "breed"
ATTR_SEX = "sex"
ATTR_BIRTH_DATE = "birth_date"
ATTR_ARRIVAL_DATE = "arrival_date"
ATTR_STATUS = "status"

RECURRENCE_ONCE = "once"
RECURRENCE_DAILY = "daily"
RECURRENCE_WEEKLY = "weekly"
RECURRENCE_MONTHLY = "monthly"
RECURRENCE_TYPES = {
    RECURRENCE_ONCE,
    RECURRENCE_DAILY,
    RECURRENCE_WEEKLY,
    RECURRENCE_MONTHLY,
}
