create_animal:
  fields:
    name:
      required: true
      example: Ada
      selector:
        text:
    species:
      required: true
      example: Chicken
      selector:
        text:
    breed:
      example: Sussex
      selector:
        text:
    sex:
      selector:
        select:
          options:
            - male
            - female
            - other
          translation_key: animal_sex
          mode: dropdown
    birth_date:
      selector:
        date:
    arrival_date:
      selector:
        date:

update_animal:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: animal_health
    name:
      selector:
        text:
    species:
      selector:
        text:
    breed:
      selector:
        text:
    sex:
      selector:
        select:
          options:
            - male
            - female
            - other
          translation_key: animal_sex
          mode: dropdown
    birth_date:
      selector:
        date:
    arrival_date:
      selector:
        date:

archive_animal:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: animal_health

restore_animal:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: animal_health
