AH034.taskManagementRow097=function(task){
 const duplicate=`<button type="button" data-action="task-duplicate-034" data-id="${esc(task.id)}" title="${esc(this.t("taskDuplicate034"))}" aria-label="${esc(this.t("taskDuplicate034"))}"><ha-icon icon="mdi:content-copy"></ha-icon></button>`;
 if(!this.taskCompleted034(task)){
  const html=AH034Base.taskManagementRow097.call(this,task);
  return html.replace('<div class="taskDefinitionActions097">',`<div class="taskDefinitionActions097">${duplicate}`)
 }
 const target=typeof this.taskTarget097==="function"?this.taskTarget097(task):(task.animal_name||task.group_name||this.t("general")),recurrence=String(task.recurrence_type||"once")!=="once"&&typeof this.recurrenceLabel095==="function"?this.recurrenceLabel095(task):this.l(task.recurrence_type||"once"),meta=[target,this.l(task.task_kind||"reminder"),recurrence].filter(Boolean).join(" · "),stats=this.taskOccurrenceStats034(task),completedAt=stats.lastCompleted?.completed_at||stats.lastCompleted?.updated_at||stats.lastCompleted?.scheduled_for||task.last_completed_at||"",completedText=completedAt?`${this.t("lastCompleted097")}: ${this.fmt(completedAt,true)}`:this.t("taskCompleted034");
 return`<article class="taskDefinition097 completed034"><ha-icon icon="${I[task.task_kind]||I.reminder}"></ha-icon><div class="taskDefinitionMain097"><b>${esc(task.title)}</b><span>${esc(meta)}</span><span class="taskBadge097 completedBadge034">${esc(completedText)}</span></div><div class="taskDefinitionActions097">${duplicate}<button type="button" data-action="task-continue-034" data-id="${esc(task.id)}" title="${esc(this.t("taskContinue034"))}" aria-label="${esc(this.t("taskContinue034"))}"><ha-icon icon="mdi:calendar-refresh-outline"></ha-icon></button></div></article>`
};
AH034.tasks=function(){
 const q=String(this.filter||"").trim().toLocaleLowerCase(),items=this.taskDefinitionItems097().filter(task=>!q||[task.title,task.description,typeof this.taskTarget097==="function"?this.taskTarget097(task):"",task.task_kind,task.recurrence_type,task.is_active?"active":"inactive"].some(value=>String(value||"").toLocaleLowerCase().includes(q))).sort((a,b)=>Number(b.is_active)-Number(a.is_active)||String(a.title||"").localeCompare(String(b.title||""),undefined,{sensitivity:"base"})),completed=items.filter(task=>this.taskCompleted034(task)),open=items.filter(task=>!this.taskCompleted034(task)),series=open.filter(task=>task.is_active&&String(task.recurrence_type||"once")!=="once"),oneOff=open.filter(task=>task.is_active&&String(task.recurrence_type||"once")==="once"),inactive=open.filter(task=>!task.is_active),actions=`<button class="primary" data-action="create-task"><ha-icon icon="mdi:clipboard-plus"></ha-icon>${this.t("createTask")}</button>`;
 const content=[this.taskManagementGroup097(this.t("activeSeries097"),series),this.taskManagementGroup097(this.t("activeOneOff097"),oneOff),this.taskManagementGroup097(this.t("taskCompleted034"),completed),this.taskManagementGroup097(this.t("inactiveTasks097"),inactive)].join("")||`<section class="card">${this.empty("noManagedTasks097")}</section>`;
 return`${this.heading("taskManagement097",actions)}<section class="card taskManagementIntro097"><p>${this.t("taskManagementHint097")}</p>${completed.length?`<small>${this.t("taskCompletedHint034")}</small>`:""}</section>${content}`
};
