Object.assign(T,{
 calendarPrevious0816:["Vorheriger Monat","Previous month"],
 calendarNext0816:["Nächster Monat","Next month"],
 calendarEntries0816:["Einträge","Entries"],
 calendarAnimals0816:["Tiere","Animals"],
 allEntryTypes0816:["Alle Eintragsarten","All entry types"],
 allAnimals0816:["Alle Tiere","All animals"],
 scopeToday0816:["Heute","Today"],
 scopeWeek0816:["Diese Woche","This week"],
 scopeMonth0816:["Dieser Monat","This month"],
 todayRelevant0816:["Heute relevant","Relevant today"],
 tomorrowRelevant0816:["Morgen relevant","Relevant tomorrow"],
 restWeekRelevant0816:["Rest diese Woche","Rest of this week"],
 nextWeekRelevant0816:["Nächste Woche","Next week"],
 restMonthRelevant0816:["Rest diesen Monat","Rest of this month"],
 nothingToday0816:["Heute ist nichts relevant.","Nothing is relevant today."],
 nothingRange0816:["Im gewählten Zeitraum ist nichts relevant.","Nothing is relevant in the selected period."],
 overviewRange0816:["Zeitraum","Period"]
});
const AH0816=AnimalHealthPanel.prototype;
const AH0816Base={calendar:AH0816.calendar,overview:AH0816.overview,handleClick:AH0816.handleClick,handleChange:AH0816.handleChange};
AH0816.calendarMonthStart0816=function(){const today=this.utcDate0815(this.d?.today)||new Date(),offset=Number(this.calendarOffset0816||0);return new Date(Date.UTC(today.getUTCFullYear(),today.getUTCMonth()+offset,1))};
AH0816.calendarFilteredTasks0816=function(){const kind=this.calendarKind0816||"all",animal=this.calendarAnimal0816||"all";return(this.d?.tasks||[]).filter(task=>task.is_active).filter(task=>kind==="all"||String(task.task_kind||"reminder")===kind).filter(task=>animal==="all"||String(task.animal_id||"")===animal)};
AH0816.calendar=function(){
 const monthStart=this.calendarMonthStart0816(),today=this.utcDate0815(this.d?.today)||new Date(),offset=(monthStart.getUTCDay()+6)%7,gridStart=this.addDays0815(monthStart,-offset),locale=this.lang()?"en-GB":"de-CH",monthLabel=new Intl.DateTimeFormat(locale,{month:"long",year:"numeric",timeZone:"UTC"}).format(monthStart),weekdays=Array.from({length:7},(_,index)=>new Intl.DateTimeFormat(locale,{weekday:"short",timeZone:"UTC"}).format(this.addDays0815(new Date(Date.UTC(2026,7,10)),index))),tasks=this.calendarFilteredTasks0816(),todayKey=this.dateKey0815(today),kindValue=this.calendarKind0816||"all",animalValue=this.calendarAnimal0816||"all";
 const kinds=[...new Set((this.d?.tasks||[]).map(task=>String(task.task_kind||"reminder")))].sort((a,b)=>this.l(a).localeCompare(this.l(b))),animals=[...(this.d?.animals||[])].sort((a,b)=>String(a.name||"").localeCompare(String(b.name||"")));
 const cells=Array.from({length:42},(_,index)=>{const day=this.addDays0815(gridStart,index),key=this.dateKey0815(day),dim=day.getUTCMonth()!==monthStart.getUTCMonth(),items=tasks.filter(task=>this.taskOccurs0815(task,key)),icons=items.slice(0,8).map(task=>{const target=task.animal_name||task.group_name||this.t("general"),title=[task.title,target].filter(Boolean).join(" · ");return`<span class="calendarIcon0816" title="${esc(title)}"><ha-icon icon="${I[task.task_kind]||I.reminder}"></ha-icon></span>`}).join("");return`<div class="calendarCell0816 ${dim?"dim0816":""} ${key===todayKey?"today0816":""}"><time>${day.getUTCDate()}</time><div class="calendarIcons0816">${icons}${items.length>8?`<small>+${items.length-8}</small>`:""}</div></div>`}).join("");
 return`${this.heading("calendar")}<section class="card calendarCard0816"><div class="calendarToolbar0816"><div class="calendarNav0816"><button data-action="calendar-prev-0816" title="${this.t("calendarPrevious0816")}"><ha-icon icon="mdi:chevron-left"></ha-icon></button><button data-action="calendar-today-0816">${this.t("calendarToday0815")}</button><button data-action="calendar-next-0816" title="${this.t("calendarNext0816")}"><ha-icon icon="mdi:chevron-right"></ha-icon></button></div><h2>${esc(monthLabel)}</h2><div class="calendarFilters0816"><label><span>${this.t("calendarEntries0816")}</span><select data-calendar-kind><option value="all" ${kindValue==="all"?"selected":""}>${this.t("allEntryTypes0816")}</option>${kinds.map(kind=>`<option value="${esc(kind)}" ${kindValue===kind?"selected":""}>${esc(this.l(kind))}</option>`).join("")}</select></label><label><span>${this.t("calendarAnimals0816")}</span><select data-calendar-animal><option value="all" ${animalValue==="all"?"selected":""}>${this.t("allAnimals0816")}</option>${animals.map(animal=>`<option value="${esc(animal.id)}" ${animalValue===String(animal.id)?"selected":""}>${esc(animal.name)}</option>`).join("")}</select></label></div></div><div class="calendarWeekdays0816">${weekdays.map(day=>`<b>${esc(day)}</b>`).join("")}</div><div class="calendarGrid0816">${cells}</div></section><style>.calendarToolbar0816{display:grid;grid-template-columns:auto 1fr auto;align-items:end;gap:14px;margin-bottom:12px}.calendarToolbar0816 h2{text-align:center;margin:0 0 5px}.calendarNav0816{display:flex;gap:5px;align-items:center}.calendarNav0816 button{padding:7px 9px}.calendarFilters0816{display:flex;gap:8px;align-items:end;justify-content:flex-end}.calendarFilters0816 label{display:flex;flex-direction:column;gap:3px;min-width:145px}.calendarFilters0816 label span{font-size:.72rem;color:var(--secondary-text-color)}.calendarFilters0816 select{min-height:35px}.calendarWeekdays0816,.calendarGrid0816{display:grid;grid-template-columns:repeat(7,minmax(0,1fr))}.calendarWeekdays0816 b{text-align:center;padding:5px;font-size:.78rem;opacity:.65}.calendarCell0816{min-height:76px;padding:6px;border:1px solid var(--divider-color);display:flex;flex-direction:column;gap:5px}.calendarCell0816.dim0816{opacity:.42}.calendarCell0816.today0816{box-shadow:inset 0 0 0 2px var(--primary-color)}.calendarCell0816 time{font-weight:600}.calendarIcons0816{display:flex;flex-wrap:wrap;gap:3px}.calendarIcon0816{padding:3px;border-radius:5px;background:var(--secondary-background-color)}@media(max-width:760px){.calendarToolbar0816{grid-template-columns:1fr}.calendarToolbar0816 h2{grid-row:1;text-align:left}.calendarNav0816{grid-row:2}.calendarFilters0816{grid-row:3;justify-content:stretch}.calendarFilters0816 label{flex:1;min-width:0}.calendarCell0816{min-height:56px;padding:3px}.calendarIcon0816{padding:1px}.calendarIcon0816 ha-icon{width:18px;height:18px}}</style>`
};
AH0816.occurrenceDate0816=function(item){return String(item?.scheduled_date||item?.scheduled_local||item?.scheduled_for||"").slice(0,10)};
AH0816.occurrenceForTaskDate0816=function(taskId,key){return(this.d?.occurrences||[]).find(item=>String(item.task_id)===String(taskId)&&this.occurrenceDate0816(item)===key)||null};
AH0816.virtualRelevantItems0816=function(start,end){
 const result=[],seen=new Set();if(!start||!end||start>end)return result;for(let day=new Date(start);day<=end;day=this.addDays0815(day,1)){const key=this.dateKey0815(day);for(const task of this.d?.tasks||[]){if(!task.is_active||!this.taskOccurs0815(task,key))continue;const occurrence=this.occurrenceForTaskDate0816(task.id,key);if(occurrence&&occurrence.status!=="pending")continue;const id=`${task.id}|${key}`;if(seen.has(id))continue;seen.add(id);result.push({task,key,occurrence,isOverdue:false})}}
 return result
};
AH0816.todayRelevantItems0816=function(today){const key=this.dateKey0815(today),items=this.virtualRelevantItems0816(today,today),seen=new Set(items.map(item=>`${item.task.id}|${item.key}`));for(const occurrence of(this.d?.occurrences||[]).filter(item=>item.status==="pending"&&item.is_overdue)){const task=(this.d?.tasks||[]).find(candidate=>String(candidate.id)===String(occurrence.task_id));if(!task)continue;const occurrenceKey=this.occurrenceDate0816(occurrence),id=`${task.id}|${occurrenceKey}`;if(seen.has(id))continue;seen.add(id);items.unshift({task,key:occurrenceKey,occurrence,isOverdue:true})}return items};
AH0816.relevantRow0816=function(item){const task=item.task,occurrence=item.occurrence,target=task.animal_name||task.group_name||this.t("general"),dateText=this.fmt(item.key),time=task.due_time?` · ${esc(String(task.due_time).slice(0,5))}`:"",canExecute=Boolean(occurrence&&(item.isOverdue||item.key===String(this.d?.today||""))),urgent=item.isOverdue?" urgent":"";return`<div class="nextTask${urgent}"><div class="nextTaskIcon"><ha-icon icon="${I[task.task_kind]||I.reminder}"></ha-icon></div><div class="nextTaskMain static0816"><b>${esc(task.title)}</b><span>${esc(target)} · ${dateText}${time}</span></div>${canExecute?`<button class="primary compactExecute" data-action="execute" data-id="${esc(occurrence.id)}">${this.t("execute")}</button>`:""}</div>`};
AH0816.relevantGroup0816=function(label,items){if(!items.length)return"";return`<div class="relevantGroup0816"><h3>${esc(label)}</h3>${items.map(item=>this.relevantRow0816(item)).join("")}</div>`};
AH0816.overviewGroups0816=function(scope){
 const today=this.utcDate0815(this.d?.today)||new Date(),monthEnd=new Date(Date.UTC(today.getUTCFullYear(),today.getUTCMonth()+1,0)),weekIndex=(today.getUTCDay()+6)%7,weekEnd=this.addDays0815(today,6-weekIndex),tomorrow=this.addDays0815(today,1),groups=[{label:this.t("todayRelevant0816"),items:this.todayRelevantItems0816(today)}];
 if(scope==="today")return groups;
 const rangeEnd=scope==="week"?weekEnd:monthEnd;
 if(tomorrow<=rangeEnd)groups.push({label:this.t("tomorrowRelevant0816"),items:this.virtualRelevantItems0816(tomorrow,tomorrow)});
 const restWeekStart=this.addDays0815(today,2),restWeekEnd=weekEnd<rangeEnd?weekEnd:rangeEnd;if(restWeekStart<=restWeekEnd)groups.push({label:this.t("restWeekRelevant0816"),items:this.virtualRelevantItems0816(restWeekStart,restWeekEnd)});
 if(scope==="month"){
  const nextWeekStart=this.addDays0815(weekEnd,1),nextWeekEnd=this.addDays0815(nextWeekStart,6),clippedNextEnd=nextWeekEnd<monthEnd?nextWeekEnd:monthEnd;if(nextWeekStart<=clippedNextEnd)groups.push({label:this.t("nextWeekRelevant0816"),items:this.virtualRelevantItems0816(nextWeekStart,clippedNextEnd)});
  const restMonthStart=this.addDays0815(clippedNextEnd,1);if(restMonthStart<=monthEnd)groups.push({label:this.t("restMonthRelevant0816"),items:this.virtualRelevantItems0816(restMonthStart,monthEnd)})
 }
 return groups
};
AH0816.overview=function(){
 const scope=this.overviewScope0816||"today",groups=this.overviewGroups0816(scope),count=groups.reduce((sum,group)=>sum+group.items.length,0),scopeLabel=scope==="week"?this.t("scopeWeek0816"):scope==="month"?this.t("scopeMonth0816"):this.t("scopeToday0816"),emptyText=scope==="today"?this.t("nothingToday0816"):this.t("nothingRange0816");
 const content=count?groups.map(group=>this.relevantGroup0816(group.label,group.items)).join(""):`<div class="nothingDue"><ha-icon icon="mdi:check-circle-outline"></ha-icon><span>${emptyText}</span></div>`;
 return`${this.heading("overview")}<section class="actionNow actionNow0816 ${count?"hasUrgent":""}"><div class="actionNowHead actionNowHead0816"><div><small>${scopeLabel}</small><h2>${this.t("actionNow")}</h2></div><label class="scopeEar0816" title="${this.t("overviewRange0816")}"><select data-overview-scope><option value="today" ${scope==="today"?"selected":""}>${this.t("scopeToday0816")}</option><option value="week" ${scope==="week"?"selected":""}>${this.t("scopeWeek0816")}</option><option value="month" ${scope==="month"?"selected":""}>${this.t("scopeMonth0816")}</option></select></label></div>${content}</section><section class="quickCaptureCard"><h2>${this.t("quickCapture")}</h2><div class="quickCaptureGrid"><button data-action="record-weight"><ha-icon icon="mdi:scale"></ha-icon><span>${this.t("recordWeight")}</span></button><button data-action="record-symptom"><ha-icon icon="mdi:alert-circle-outline"></ha-icon><span>${this.t("recordSymptom")}</span></button><button data-action="record-product"><ha-icon icon="mdi:pill"></ha-icon><span>${this.t("recordProduct")}</span></button><button data-action="record-event"><ha-icon icon="mdi:note-plus-outline"></ha-icon><span>${this.t("recordGeneral")}</span></button><button data-action="create-task"><ha-icon icon="mdi:clipboard-plus-outline"></ha-icon><span>${this.t("createTask")}</span></button><button data-action="ai-assist"><ha-icon icon="mdi:creation-outline"></ha-icon><span>${this.t("aiAssist")}</span></button></div></section><style>.actionNow0816{position:relative}.actionNowHead0816{align-items:flex-start}.scopeEar0816{margin:-14px -14px 0 0}.scopeEar0816 select{appearance:auto;border-radius:0 14px 0 10px;border:1px solid var(--divider-color);background:var(--secondary-background-color);padding:7px 10px;min-height:34px}.relevantGroup0816{margin-top:12px}.relevantGroup0816 h3{font-size:.82rem;text-transform:uppercase;letter-spacing:.04em;color:var(--secondary-text-color);margin:12px 0 5px}.relevantGroup0816+.relevantGroup0816{border-top:1px solid var(--divider-color);padding-top:5px}.nextTaskMain.static0816{cursor:default;text-align:left}@media(max-width:520px){.scopeEar0816{margin:-10px -10px 0 0}.scopeEar0816 select{max-width:130px}}</style>`
};
AH0816.handleClick=async function(event){const button=event.composedPath().find(node=>node?.dataset?.action),action=button?.dataset?.action;if(action==="calendar-prev-0816"){this.calendarOffset0816=Number(this.calendarOffset0816||0)-1;this.render();return}if(action==="calendar-next-0816"){this.calendarOffset0816=Number(this.calendarOffset0816||0)+1;this.render();return}if(action==="calendar-today-0816"){this.calendarOffset0816=0;this.render();return}return AH0816Base.handleClick.call(this,event)};
AH0816.handleChange=function(event){const input=event.composedPath()[0];if(input?.dataset&&"calendarKind" in input.dataset){this.calendarKind0816=input.value||"all";this.render();return}if(input?.dataset&&"calendarAnimal" in input.dataset){this.calendarAnimal0816=input.value||"all";this.render();return}if(input?.dataset&&"overviewScope" in input.dataset){this.overviewScope0816=input.value||"today";this.render();return}return AH0816Base.handleChange.call(this,event)};
