Object.assign(T,{
 tags:["Tags","Tags"],tag:["Tag","Tag"],allTags:["Alle Tags","All tags"],createTag:["Tag anlegen","Create tag"],editTag:["Tag bearbeiten","Edit tag"],tagName:["Name des Tags","Tag name"],tagDescription:["Beschreibung","Description"],primaryGroup:["Primäre Tiergruppe","Primary animal group"],createGroupInline:["Neue Tiergruppe anlegen …","Create new animal group …"],animalPhoto:["Tierbild","Animal photo"],chooseAnimalPhoto:["Tierbild auswählen","Choose animal photo"],replaceAnimalPhoto:["Tierbild ersetzen","Replace animal photo"],removeAnimalPhoto:["Tierbild entfernen","Remove animal photo"],healthTimeline:["Gesundheitschronik","Health timeline"],activityTimeline:["Aktivitätsverlauf","Activity timeline"],allTimeline:["Alle Einträge","All records"],seriesPause:["Serie pausieren","Pause series"],seriesResume:["Serie fortsetzen","Resume series"],seriesPaused:["Serie pausiert","Series paused"],documentReminder:["Erledigung in Chronik dokumentieren","Document completion in timeline"],lastMeasurement:["Letzte Messung","Previous measurement"],newMeasurement:["Neue Messung","New measurement"],taskFilterOverdue:["Filter: überfällig","Filter: overdue"],taskFilterToday:["Filter: heute fällig","Filter: due today"],taskFilterPending:["Filter: offene Aufgaben","Filter: open tasks"],clearFilter:["Filter löschen","Clear filter"],activeOnly:["Nur aktive Tiere","Active animals only"],treatment_action:["Behandlung","Treatment"],photoUploadFailed:["Tierbild konnte nicht gespeichert werden.","Animal photo could not be saved."]
});
S.treatment="record_task_treatment";
I.treatment="mdi:medical-bag";
const AH080=AnimalHealthPanel.prototype;
const AH080Base={
 load:AH080.load,
 loadDetail:AH080.loadDetail,
 render:AH080.render,
 form:AH080.form,
 handleClick:AH080.handleClick,
 handleChange:AH080.handleChange,
 handleSubmit:AH080.handleSubmit,
 overview:AH080.overview,
 animals:AH080.animals,
 animalCard:AH080.animalCard,
 animalDetail:AH080.animalDetail,
 stat:AH080.stat,
 tasks:AH080.tasks,
 timeline:AH080.timeline,
 eventRow:AH080.eventRow,
 eventDetail:AH080.eventDetail,
 occRow:AH080.occRow,
 animalChecks:AH080.animalChecks,
 execForm:AH080.execForm,
 saveExecution:AH080.saveExecution,
 groupLifecycleForm:AH080.groupLifecycleForm
};
AH080.tagById=function(id){return(this.v080?.tags||[]).find(tag=>String(tag.id)===String(id))||null};
AH080.tagIdsFor=function(animalId){return this.v080?.tag_memberships?.[animalId]||[]};
AH080.profileIdFor=function(animalId){return this.v080?.profiles?.[animalId]||null};
AH080.profileUrlFor=function(animalId){return this.profileUrls?.[animalId]||null};
AH080.decorateV080=function(){
 const tags=new Map((this.v080?.tags||[]).map(tag=>[String(tag.id),tag]));
 const apply=animal=>{if(!animal)return;animal.tag_ids=this.tagIdsFor(animal.id);animal.tags=animal.tag_ids.map(id=>tags.get(String(id))).filter(Boolean);animal.profile_image_id=this.profileIdFor(animal.id);animal.profile_url=this.profileUrlFor(animal.id)};
 for(const animal of this.d?.animals||[])apply(animal);apply(this.detail?.animal)
};
AH080.loadV080=async function(){
 this.v080=await this.ws(`${D}/v080/state`);this.profileUrls={};
 const profiles=this.v080?.profiles||{},entries=Object.entries(profiles).filter(([,id])=>id);
 await Promise.all(entries.map(async([animalId,attachmentId])=>{try{const result=await this.ws(`${D}/download`,{kind:"attachment",resource_id:attachmentId});this.profileUrls[animalId]=result.url}catch(_error){this.profileUrls[animalId]=null}}));
 this.decorateV080()
};
AH080.load=async function(){await AH080Base.load.call(this);if(!this.h||!this.d)return;try{await this.loadV080()}catch(error){this.v080={tags:[],tag_memberships:{},profiles:{}};this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}this.render()};
AH080.loadDetail=async function(id,r=true){await AH080Base.loadDetail.call(this,id,false);this.decorateV080();if(r)this.render()};
AH080.animalVisual=function(animal,extra=""){const url=animal?.profile_url||this.profileUrlFor(animal?.id);return url?`<img class="animalAvatar ${extra}" src="${esc(url)}" alt="${esc(animal?.name||"")}">`:this.speciesVisual(animal?.species)};
AH080.profileThumb=function(animalId){const animal=this.animal(animalId),url=animal?.profile_url||this.profileUrlFor(animalId);return url?`<img class="miniAvatar" src="${esc(url)}" alt="${esc(animal?.name||"")}">`:""};
AH080.tagChips=function(animal){return animal?.tags?.length?`<div class="tagChips">${animal.tags.map(tag=>`<span>${esc(tag.name)}</span>`).join("")}</div>`:""};
AH080.primaryGroupSelect=function(value=""){const groups=this.activeGroups(),options=groups.map(group=>`<option value="${esc(group.id)}" ${group.id===value?"selected":""}>${esc(group.name)}</option>`).join("");return`<label><span>${this.t("primaryGroup")}</span><select name="group_id" required><option value="" ${value?"":"selected"} disabled>–</option>${options}<option value="__new__">＋ ${this.t("createGroupInline")}</option></select></label>`};
AH080.tagChoices=function(selected=[]){const tags=this.v080?.tags||[];return`<fieldset class="wide tagChoices"><legend>${this.t("tags")}</legend>${tags.length?tags.map(tag=>`<label><input type="checkbox" name="tag_ids" value="${esc(tag.id)}" ${selected.includes(tag.id)?"checked":""}><span>${esc(tag.name)}</span></label>`).join(""):`<small>${this.t("createTag")}</small>`}</fieldset>`};
AH080.profileField=function(animal){const url=animal?.profile_url||this.profileUrlFor(animal?.id),label=url?this.t("replaceAnimalPhoto"):this.t("chooseAnimalPhoto");return`<fieldset class="wide profileField"><legend>${this.t("animalPhoto")}</legend>${url?`<img class="profilePreview" src="${esc(url)}" alt="${esc(animal?.name||"")}">`:this.speciesVisual(animal?.species)}<label class="fileChoice"><ha-icon icon="mdi:image-plus-outline"></ha-icon><span>${label}</span><input type="file" name="profile_image" accept="image/*"></label>${url&&animal?.id?`<button type="button" data-action="remove-animal-photo" data-id="${esc(animal.id)}"><ha-icon icon="mdi:image-remove-outline"></ha-icon>${this.t("removeAnimalPhoto")}</button>`:""}</fieldset>`};
AH080.groupLifecycleForm=function(modal){
 const group=this.groupById(modal.groupId)||{},members=Object.entries(this.features?.memberships||{}).filter(([,groupId])=>groupId===modal.groupId).map(([animalId])=>this.animal(animalId)).filter(Boolean),targets=this.activeGroups().filter(item=>item.id!==modal.groupId),mode=modal.mode||"archive",title=mode==="delete"?this.t("deleteGroup"):this.t("archiveGroup"),question=mode==="delete"?this.t("confirmDeleteGroup"):this.t("confirmArchiveGroup");
 const initial=targets.length?"existing":"new";
 const disposition=members.length?`<p class="wide">${this.t("groupMembersAction")}</p><fieldset class="wide disposition"><label><input type="radio" name="disposition" value="existing" ${initial==="existing"?"checked":""}><span>${this.t("moveToExistingGroup")}</span></label><label><input type="radio" name="disposition" value="new" ${initial==="new"?"checked":""}><span>${this.t("moveToNewGroup")}</span></label></fieldset><label class="wide" data-existing-target ${initial==="existing"?"":"hidden"}><span>${this.t("targetGroup")}</span><select name="target_group_id">${targets.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join("")}</select></label><div class="wide newGroupFields" data-new-target ${initial==="new"?"":"hidden"}>${this.field("newGroupName","new_group_name")}${this.speciesSelect("",false)}</div><div class="wide memberNames">${members.map(item=>`<span>${esc(item.name)}</span>`).join("")}</div>`:"";
 return`<h2>${title}: ${esc(group.name||"")}</h2><form data-form="group-lifecycle"><input type="hidden" name="group_id" value="${esc(modal.groupId)}"><input type="hidden" name="mode" value="${esc(mode)}"><p class="wide">${question}</p>${disposition}${this.buttons(mode==="delete"?"delete":"archive")}</form>`
};
AH080.weightForm=function(modal){const animal=this.animal(modal.animalId)||(this.d?.animals||[])[0],weight=animal?.latest_weight;return`<h2>${this.t("recordWeight")}</h2><form data-form="weight">${this.animalSel(modal.animalId)}<label class="wide"><span>${this.t("weight")}</span><div class="weightStepper080"><button type="button" data-action="weight-step-080" data-delta="-0.10">−0,10 kg</button><button type="button" data-action="weight-step-080" data-delta="-0.01">−0,01 kg</button><input name="weight" type="number" value="${esc(weight?.original_value||"")}" required min="0.000001" step="any"><button type="button" data-action="weight-step-080" data-delta="0.01">+0,01 kg</button><button type="button" data-action="weight-step-080" data-delta="0.10">+0,10 kg</button></div></label>${this.sel("dose_unit","weight_unit",this.c.weight_units,weight?.original_unit||"kg","required")}${this.field("occurred_at","occurred_at","datetime-local")}<small class="hint">${this.t("emptyNow")}</small>${this.area("notes","notes")}${this.fileFields()}${this.buttons()}</form>`};
AH080.form=function(){
 const modal=this.modal;
 if(modal?.type==="create-tag"||modal?.type==="edit-tag"){
  const tag=modal.type==="edit-tag"?this.tagById(modal.tagId)||{}:{};return`<h2><ha-icon icon="mdi:tag-outline"></ha-icon>${this.t(modal.type==="edit-tag"?"editTag":"createTag")}</h2><form data-form="tag">${tag.id?`<input type="hidden" name="tag_id" value="${esc(tag.id)}">`:""}${this.field("tagName","name","text",tag.name,"required autofocus")}${this.area("tagDescription","description",tag.description)}${tag.id?`<div class="wide"><button type="button" class="danger" data-action="delete-tag" data-id="${esc(tag.id)}"><ha-icon icon="mdi:delete-outline"></ha-icon>${this.t("delete")}</button></div>`:""}${this.buttons()}</form>`
 }
 if(modal?.type==="record-weight")return this.weightForm(modal);
 if(modal?.type==="create-animal"||modal?.type==="edit-animal"){
  const current=modal.type==="edit-animal"?this.animal(modal.animalId)||{}:{},draft=this.animalDraft&&this.animalDraftModal===modal.type?this.animalDraft:null,animal=draft||current,groupId=draft?.group_id??(modal.type==="edit-animal"?current.group_id||"":modal.groupId||""),group=this.groupById(groupId);let species=animal.species||"";if(!species&&group?.species)species=this.speciesLabel(group.species);const selectedTags=draft?.tag_ids?([].concat(draft.tag_ids)):this.tagIdsFor(current.id);
  return`<h2>${this.animalVisual(current)}${this.t(modal.type==="edit-animal"?"edit":"createAnimal")}</h2><form data-form="animal">${current.id?`<input type="hidden" name="animal_id" value="${esc(current.id)}">`:""}${this.field("name","name","text",animal.name,"required autofocus")}${this.field("species","species","text",species,'required list="species"')}${this.field("breed","breed","text",animal.breed,'list="breeds"')}${this.field("color","color","text",animal.color,'list="colors"')}${this.sexChoices(animal.sex||"")}${this.field("birth_date","birth_date","date",animal.birth_date)}${this.field("arrival_date","arrival_date","date",animal.arrival_date)}${this.primaryGroupSelect(groupId)}${this.tagChoices(selectedTags)}${this.profileField(current)}${this.animalLists(species,animal.breed)}${this.buttons()}</form>`
 }
 return AH080Base.form.call(this)
};
AH080.execForm=function(occurrence){
 let html=AH080Base.execForm.call(this,occurrence),kind=occurrence?.task_kind||"reminder",planned=occurrence?.planned||{};
 if(kind==="treatment"){
  const marker=`<input type="hidden" name="occurrence_id" value="${occurrence.id}">`;html=html.replace(marker,`${marker}${this.field("treatment_action","treatment_action","text",planned.treatment_action||occurrence.task_title,"required")}${this.field("outcome","outcome")}`)
 }
 if(kind==="reminder"&&occurrence?.animal_id){html=html.replace('<div class="buttons wide">',`<label class="wide reminderChronicle"><input type="checkbox" name="document_in_timeline" value="1"><span>${this.t("documentReminder")}</span></label><div class="buttons wide">`)}
 return html
};
AH080.saveExecution=function(form,values){
 const occurrence=this.occ(values.occurrence_id),kind=occurrence?.task_kind||"reminder";
 if(kind!=="reminder"&&kind!=="treatment")return AH080Base.saveExecution.call(this,form,values);
 const payload={occurrence_id:occurrence.id};for(const key of["performed_at","deviation_reason","notes"])if(values[key])payload[key]=values[key];
 if(kind==="reminder"){if(form.querySelector('[name="document_in_timeline"]:checked'))payload.document_in_timeline=true;return this.svc(S.reminder,payload,true)}
 if(values.treatment_action)payload.treatment_action=values.treatment_action;if(values.outcome)payload.outcome=values.outcome;return this.svc(S.treatment,payload,true)
};
AH080.handleChange=function(event){
 AH080Base.handleChange.call(this,event);const input=event.composedPath()[0],form=input?.form;
 if(form?.dataset.form==="animal"&&input.name==="group_id"&&input.value==="__new__"){
  const values=data(form);values.tag_ids=[...form.querySelectorAll('[name="tag_ids"]:checked')].map(item=>item.value);values.group_id="";this.animalDraft=values;this.animalDraftModal=this.modal?.type;this.returnToAnimal={type:this.modal?.type,animalId:this.modal?.animalId};this.open("create-group",{fromAnimal:true})
 }
};
AH080.uploadAnimalPhoto=async function(form,animalId){const file=form.elements.profile_image?.files?.[0];if(!file)return;const max=this.features?.max_attachment_size_bytes||15728640;if(file.size>max)throw Error(this.t("fileTooLarge"));const target=await this.ws(`${D}/attachments/upload`,{animal_id:animalId}),payload=new FormData();payload.append("file",file,file.name||"animal-photo.jpg");payload.append("title",this.t("animalPhoto"));const response=await fetch(target.url,{method:"POST",body:payload,credentials:"same-origin"});if(!response.ok)throw Error((await response.text())||`HTTP ${response.status}`);const attachment=await response.json();await this.ws(`${D}/animal_photo/set`,{animal_id:animalId,attachment_id:attachment.id})};
AH080.handleSubmit=async function(event){
 const form=event.composedPath().find(node=>node?.tagName==="FORM");if(!form)return;
 if(form.dataset.form==="animal"){
  event.preventDefault();const values=data(form);values.tag_ids=[...form.querySelectorAll('[name="tag_ids"]:checked')].map(item=>item.value);if(!values.group_id||values.group_id==="__new__"){this.notify(`${this.t("failed")}: ${this.t("primaryGroup")}`,true);return}this.animalDraft={...values};this.animalDraftModal=this.modal?.type;const submit=form.querySelector('button[type="submit"]');if(submit)submit.disabled=true;
  try{const result=await this.saveAnimal(values),animalId=values.animal_id||this.recordId(result);if(!animalId)throw Error("Animal ID missing from service response");await this.ws(`${D}/tags/set`,{animal_id:animalId,tag_ids:values.tag_ids});await this.uploadAnimalPhoto(form,animalId);this.animalDraft=null;this.animalDraftModal=null;await this.after()}catch(error){if(submit)submit.disabled=false;this.notify(`${this.t("failed")}: ${this.friendlyError?this.friendlyError(error):error?.message||error}`,true)}return
 }
 if(form.dataset.form==="group"&&this.modal?.fromAnimal){
  event.preventDefault();const values=data(form),payload={name:values.name,...(values.species?{species:values.species}:{}),...(values.description?{description:values.description}:{})};try{const group=await this.ws(`${D}/groups/create`,payload);this.features.groups.push(group);if(this.animalDraft)this.animalDraft.group_id=group.id;const back=this.returnToAnimal||{type:"create-animal"};this.modal={type:back.type||"create-animal",...(back.animalId?{animalId:back.animalId}:{})};this.returnToAnimal=null;this.render()}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return
 }
 if(form.dataset.form==="tag"){
  event.preventDefault();const values=data(form);try{if(values.tag_id)await this.ws(`${D}/tags/update`,{tag_id:values.tag_id,name:values.name,...(values.description?{description:values.description}:{})});else await this.ws(`${D}/tags/create`,{name:values.name,...(values.description?{description:values.description}:{})});this.modal=null;await this.load();this.notify(this.t("done"))}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return
 }
 if(form.dataset.form==="execute"){
  event.preventDefault();const values=data(form);this.busy=true;this.render();try{const occurrence=this.occ(values.occurrence_id),result=await this.saveExecution(form,values),files=this.filesFrom(form);if(files.length&&occurrence?.animal_id)await this.uploadFiles(form,occurrence.animal_id,this.recordId(result));this.busy=false;await this.after()}catch(error){this.busy=false;this.notify(`${this.t("failed")}: ${error?.message||error}`,true);this.render()}return
 }
 return AH080Base.handleSubmit.call(this,event)
};
AH080.handleClick=async function(event){
 const button=event.composedPath().find(node=>node?.dataset&&(node.dataset.action||node.dataset.view));if(!button)return;const{action,id}=button.dataset;
 if(action==="summary-filter"){const filter=button.dataset.filter;if(filter==="active"){this.view="animals";this.groupFilter="all";this.animalStatusFilter="active"}else{this.view="tasks";this.taskViewFilter=filter}this.render();return}
 if(action==="tag-filter"){this.tagFilter=id||"all";this.animalStatusFilter=null;this.render();return}
 if(action==="clear-animal-filter"){this.tagFilter="all";this.animalStatusFilter=null;this.render();return}
 if(action==="clear-task-filter"){this.taskViewFilter=null;this.render();return}
 if(action==="timeline-mode"){this.timelineMode=id||"health";this.render();return}
 if(action==="create-tag"){this.open("create-tag");return}
 if(action==="edit-tag"){this.open("edit-tag",{tagId:id});return}
 if(action==="delete-tag"){try{await this.ws(`${D}/tags/delete`,{tag_id:id});this.modal=null;await this.load();this.notify(this.t("done"))}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return}
 if(action==="remove-animal-photo"){try{await this.ws(`${D}/animal_photo/remove`,{animal_id:id});await this.load();if(this.detail?.animal?.id===id)await this.loadDetail(id);this.notify(this.t("done"))}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return}
 if(action==="weight-step-080"){const form=button.closest("form"),input=form?.elements?.weight,unit=form?.elements?.weight_unit?.value||"kg";if(!input)return;const deltaKg=Number(button.dataset.delta||0),delta=unit==="kg"?deltaKg:deltaKg*1000,decimals=unit==="kg"?2:0,current=Number(input.value||0),next=Math.max(unit==="kg"?.01:1,current+delta);input.value=next.toFixed(decimals);input.focus();return}
 if(action==="event-detail"){const record=this.eventById(id);if(record?.event_type==="weight"){this.weightPrevious=this.weightPrevious||{};try{const result=await this.ws(`${D}/v080/previous_weight`,{event_id:id});this.weightPrevious[id]=result.previous||null}catch(_error){this.weightPrevious[id]=null}}this.open("event-detail",{eventId:id});return}
 return AH080Base.handleClick.call(this,event)
};
AH080.stat=function(icon,number,key,badge=""){if(this._overviewStats){const map={activeAnimals:"active",overdue:"overdue",dueToday:"today",openTasks:"pending"},filter=map[key];if(filter)return`<button class="stat statButton ${badge}" data-action="summary-filter" data-filter="${filter}"><ha-icon icon="${icon}"></ha-icon><div><strong>${esc(number)}</strong><span>${this.t(key)}</span></div></button>`}return AH080Base.stat.call(this,icon,number,key,badge)};
AH080.overview=function(){this._overviewStats=true;let html;try{html=AH080Base.overview.call(this)}finally{this._overviewStats=false}return html.replaceAll('<button data-action="create-group">','<button class="primary" data-action="create-group">')};
AH080.animals=function(){
 const q=this.filter.toLowerCase(),groups=this.activeGroups(),tagFilter=this.tagFilter||"all";let selected=this.groupFilter||"all";if(selected!=="all"&&!groups.some(group=>group.id===selected))selected="all";
 let animals=this.d.animals.filter(animal=>!q||[animal.name,animal.species,animal.breed,animal.status,animal.id,animal.group_name,...(animal.tags||[]).map(tag=>tag.name)].some(value=>String(value||"").toLowerCase().includes(q)));if(selected!=="all")animals=animals.filter(animal=>animal.group_id===selected);if(tagFilter!=="all")animals=animals.filter(animal=>(animal.tag_ids||[]).includes(tagFilter));if(this.animalStatusFilter==="active")animals=animals.filter(animal=>animal.status==="active"&&!animal.is_archived);
 const tabs=[`<button class="${selected==="all"?"on":""}" data-action="group-filter" data-id="all">${this.t("allAnimals")}</button>`,...groups.map(group=>`<button class="${selected===group.id?"on":""}" data-action="group-filter" data-id="${esc(group.id)}">${esc(group.name)} <small>${group.animal_count}</small></button>`)].join("");
 const tagTabs=[`<span class="tagFilterItem"><button class="${tagFilter==="all"?"on":""}" data-action="tag-filter" data-id="all">${this.t("allTags")}</button></span>`,...(this.v080?.tags||[]).map(tag=>`<span class="tagFilterItem"><button class="${tagFilter===tag.id?"on":""}" data-action="tag-filter" data-id="${esc(tag.id)}">#${esc(tag.name)} <small>${tag.animal_count}</small></button><button class="tagEdit" data-action="edit-tag" data-id="${esc(tag.id)}" title="${this.t("editTag")}"><ha-icon icon="mdi:pencil-outline"></ha-icon></button></span>`)].join("");
 const manage=selected!=="all"?`<button data-action="edit-group" data-id="${esc(selected)}"><ha-icon icon="mdi:pencil-outline"></ha-icon>${this.t("editGroup")}</button><button data-action="group-archive" data-id="${esc(selected)}"><ha-icon icon="mdi:archive-arrow-down-outline"></ha-icon>${this.t("archiveGroup")}</button><button data-action="group-delete" data-id="${esc(selected)}"><ha-icon icon="mdi:delete-outline"></ha-icon>${this.t("deleteGroup")}</button>`:"";
 const activeChip=this.animalStatusFilter?`<button class="filterChip" data-action="clear-animal-filter">${this.t("activeOnly")} ×</button>`:"";
 return`${this.heading("animals",`${manage}<button data-action="create-tag"><ha-icon icon="mdi:tag-plus-outline"></ha-icon>${this.t("createTag")}</button><button class="primary" data-action="create-group"><ha-icon icon="mdi:account-group-outline"></ha-icon>${this.t("createGroup")}</button><button class="primary" data-action="create-animal"><ha-icon icon="mdi:plus-circle-outline"></ha-icon>${this.t("createAnimal")}</button>`)}${activeChip}<div class="groupTabs">${tabs}</div><div class="tagTabs">${tagTabs}</div><section class="grid">${animals.map(animal=>this.animalCard(animal)).join("")||this.empty("noAnimals")}</section>`
};
AH080.animalCard=function(animal){const weight=animal.latest_weight,next=this.d.occurrences.find(item=>item.animal_id===animal.id&&item.status==="pending");return`<article class="animal ${animal.is_archived?"muted":""}"><button class="animalHead" data-action="animal-detail" data-id="${animal.id}">${this.animalVisual(animal)}<div><h3>${esc(animal.name)}</h3><span>${esc(animal.species)}${animal.breed?` · ${esc(animal.breed)}`:""}</span>${this.tagChips(animal)}</div><b>${this.l(animal.status)}</b></button><div class="animalMeta"><span>${this.t("currentWeight")}<b>${weight?`${this.num(weight.original_value)} ${weight.original_unit}`:"–"}</b></span><span>${this.t("upcoming")}<b>${next?esc(next.task_title):"–"}</b></span></div></article>`};
AH080.animalChecks=function(animals,selectedId=this.modal?.animalId||""){return`<div class="checks wide animalChecks080">${animals.map(animal=>`<label><input type="checkbox" name="device_ids" value="${esc(animal.device_id)}" ${animal.id===selectedId?"checked":""}>${this.profileThumb(animal.id)}<span>${esc(animal.name)}</span></label>`).join("")}</div>`};
AH080.animalDetail=function(){
 if(!this.detail)return this.empty("loading");const animal=this.detail.animal,weight=animal.latest_weight,pending=this.detail.occurrences.filter(item=>item.status==="pending"),groups=this.activeGroups(),groupId=animal.group_id,animals=this.detailAnimals(groupId),pages=Math.max(1,Math.ceil(animals.length/10)),page=Math.min(Number(this.animalPage||0),pages-1),shown=animals.slice(page*10,page*10+10),profileId=animal.profile_image_id,generalAttachments=(this.detail.attachments||[]).filter(item=>!item.event_id&&item.id!==profileId);
 const groupButtons=groups.map(group=>`<button class="${groupId===group.id?"on":""}" data-action="detail-group" data-id="${esc(group.id)}">${esc(group.name)}</button>`).join("");
 const switcher=`<section class="animalSwitcher"><div class="groupTabs compact">${groupButtons}</div><div class="switchRow"><button data-action="animal-page" data-delta="-1" ${page<=0?"disabled":""}><ha-icon icon="mdi:chevron-left"></ha-icon></button><div class="animalTiles">${shown.map(item=>`<button class="animalTile ${item.id===animal.id?"on":""}" data-action="animal-detail" data-id="${esc(item.id)}">${this.animalVisual(item,"tileAvatar")}<span>${esc(item.name)}</span></button>`).join("")}</div><button data-action="animal-page" data-delta="1" ${page>=pages-1?"disabled":""}><ha-icon icon="mdi:chevron-right"></ha-icon></button></div></section>`;
 return`${this.heading("animals",`<button data-view="animals"><ha-icon icon="mdi:arrow-left"></ha-icon></button>`)}${switcher}<section class="hero">${this.animalVisual(animal,"heroAvatar")}<div><h1>${esc(animal.name)}</h1><p>${animal.group_name?`${esc(animal.group_name)} · `:""}${esc(animal.species)}${animal.breed?` · ${esc(animal.breed)}`:""} · ${this.l(animal.status)}</p>${this.tagChips(animal)}</div><div class="actions"><button data-action="export-pdf" data-id="${animal.id}"><ha-icon icon="mdi:file-pdf-box"></ha-icon>${this.t("healthPdf")}</button><button data-action="edit-animal" data-id="${animal.id}">${this.t("edit")}</button><button data-action="animal-status" data-id="${animal.id}">${this.t("changeStatus")}</button><button data-action="${animal.is_archived?"restore":"archive"}" data-id="${animal.id}">${this.t(animal.is_archived?"restore":"archive")}</button></div></section>${this.quick(animal.id)}<div class="quick"><button data-action="attach-document" data-id="${animal.id}"><ha-icon icon="mdi:paperclip"></ha-icon>${this.t("attachDocument")}</button></div><section class="stats">${this.stat("mdi:scale",weight?`${this.num(weight.original_value)} ${weight.original_unit}`:"–","currentWeight")}${this.stat("mdi:clipboard",pending.length,"openTasks")}${this.stat("mdi:calendar",animal.birth_date?this.fmt(animal.birth_date):"–","birth_date")}${this.stat("mdi:identifier",animal.id,"technicalId")}</section><section class="cols"><article class="card"><h2>${this.t("masterData")}</h2>${this.obj({group:animal.group_name,tags:(animal.tags||[]).map(tag=>tag.name),species:animal.species,breed:animal.breed,color:animal.color,sex:animal.sex,birth_date:animal.birth_date,arrival_date:animal.arrival_date,status:animal.status})}</article><article class="card"><h2>${this.t("upcoming")}</h2>${this.rows(pending.slice(0,20))}</article></section><section class="card"><h2>${this.t("documents")}</h2>${this.attachmentList(generalAttachments)}</section><section class="card"><h2>${this.t("plannedActual")}</h2>${this.detail.events.map(item=>this.eventRow(item)).join("")||this.empty("noEvents")}</section>`
};
AH080.occRow=function(occurrence){const html=AH080Base.occRow.call(this,occurrence),thumb=this.profileThumb(occurrence.animal_id);return thumb?html.replace(/(<div class="row[^"]*">)/,`$1${thumb}`):html};
AH080.eventRow=function(record){const html=AH080Base.eventRow.call(this,record),thumb=this.profileThumb(record.animal_id);return thumb?html.replace(/(<div class="row event[^>]*>)/,`$1${thumb}`):html};
AH080.tasks=function(){
 const q=this.filter.toLowerCase(),view=this.taskViewFilter||null;let occurrences=this.d.occurrences.filter(item=>!q||[item.task_title,item.animal_name,item.task_kind,item.status].some(value=>String(value||"").toLowerCase().includes(q)));if(view==="overdue")occurrences=occurrences.filter(item=>item.is_overdue);if(view==="today")occurrences=occurrences.filter(item=>item.is_today);if(view==="pending")occurrences=occurrences.filter(item=>item.status==="pending");
 const definitions=this.d.tasks.filter(task=>task.is_active===false||task.recurrence_type!=="once"||this.d.occurrences.some(item=>String(item.task_id)===String(task.id)&&item.status==="pending")),filterLabel=view?this.t(view==="overdue"?"taskFilterOverdue":view==="today"?"taskFilterToday":"taskFilterPending"):"",filterChip=view?`<button class="filterChip" data-action="clear-task-filter">${filterLabel} ×</button>`:"";
 const rows=definitions.map(task=>{const recurring=task.recurrence_type!=="once",inactive=task.is_active===false,label=recurring?this.t(inactive?"seriesResume":"seriesPause"):this.t(inactive?"activate":"deactivate"),state=inactive?` · ${this.t(recurring?"seriesPaused":"taskInactive")}`:"";return`<div class="row ${inactive?"taskInactive":""}"><ha-icon icon="${I[task.task_kind]||I.reminder}"></ha-icon><div><b>${esc(task.title)}</b><span>${esc(task.animal_name||this.t("general"))} · ${this.l(task.task_kind)}${state}</span></div><button data-action="toggle" data-id="${task.id}">${label}</button></div>`}).join("");
 return`${this.heading("tasks",`<button class="primary" data-action="create-task"><ha-icon icon="mdi:clipboard-plus"></ha-icon>${this.t("createTask")}</button>`)}${filterChip}${this.group("overdue",occurrences.filter(item=>item.is_overdue))}${this.group("dueToday",occurrences.filter(item=>item.is_today))}${this.group("upcoming",occurrences.filter(item=>item.is_upcoming).slice(0,100))}${this.group("completed",occurrences.filter(item=>item.status!=="pending").slice(0,100))}<section class="card"><h2>${this.t("tasks")}</h2>${rows||this.empty("noTasks")}</section>`
};
AH080.isHealthRecord=function(record){const health=new Set(["weight","symptom","diagnosis","treatment","medication","vaccination","veterinary_visit","care"]);return health.has(record.event_type)||(record.event_type==="observation"&&record.data?.task_execution?.task_kind==="health_check")};
AH080.timeline=function(){const mode=this.timelineMode||"health",q=this.filter.toLowerCase();let records=this.d.events.filter(record=>!q||[record.animal_name,record.title,record.event_type,record.notes,record.id].some(value=>String(value||"").toLowerCase().includes(q)));if(mode==="health")records=records.filter(record=>this.isHealthRecord(record));if(mode==="activity")records=records.filter(record=>!this.isHealthRecord(record));const tabs=`<div class="timelineTabs"><button class="${mode==="health"?"on":""}" data-action="timeline-mode" data-id="health">${this.t("healthTimeline")}</button><button class="${mode==="activity"?"on":""}" data-action="timeline-mode" data-id="activity">${this.t("activityTimeline")}</button><button class="${mode==="all"?"on":""}" data-action="timeline-mode" data-id="all">${this.t("allTimeline")}</button></div>`;return`${this.heading("timeline",`<button data-action="record-event"><ha-icon icon="mdi:note-plus"></ha-icon>${this.t("recordEvent")}</button>`)}${tabs}<section class="card">${records.map(record=>this.eventRow(record)).join("")||this.empty("noEvents")}</section>`};
AH080.weightTransition=function(record){if(record?.event_type!=="weight"||record.value==null)return"";const previous=this.weightPrevious?.[record.id],previousValue=previous?.value!=null?`${this.num(previous.value)} ${esc(previous.unit||record.unit||"")}`:"–",current=`${this.num(record.value)} ${esc(record.unit||"")}`;return`<section class="statusTransition weightTransition"><div><small>${this.t("lastMeasurement")}</small><b>${previousValue}</b></div><ha-icon icon="mdi:arrow-right"></ha-icon><div><small>${this.t("newMeasurement")}</small><b>${current}</b></div></section>`};
AH080.eventDetail=function(id){const record=this.eventById(id);if(!record)return AH080Base.eventDetail.call(this,id);let html=AH080Base.eventDetail.call(this,id),transition=this.weightTransition(record);if(transition)html=html.replace('<div class="eventDetail">',`<div class="eventDetail">${transition}`);return html};
const AH080_CSS=`
.statButton{width:100%;text-align:left;appearance:none;font:inherit;color:inherit;cursor:pointer}.statButton:hover,.statButton:focus-visible,.animalHead:hover,.animalHead:focus-visible,.animalTile:hover,.animalTile:focus-visible,.groupTabs button:hover,.tagTabs button:hover{outline:2px solid color-mix(in srgb,var(--primary-color) 55%,transparent);outline-offset:-2px}.statButton:active,.animalHead:active,.animalTile:active{transform:translateY(1px)}
.tagTabs,.timelineTabs{display:flex;gap:8px;overflow:auto;margin:0 0 14px}.tagFilterItem{display:inline-flex;flex:0 0 auto}.tagFilterItem>button:first-child{border-radius:9px 0 0 9px}.tagFilterItem .tagEdit{border-radius:0 9px 9px 0;padding:8px}.tagTabs button.on,.timelineTabs button.on{border-color:var(--primary-color);color:var(--primary-color);background:color-mix(in srgb,var(--primary-color) 10%,var(--card-background-color))}.tagChips{display:flex;gap:5px;flex-wrap:wrap;margin-top:5px}.tagChips span{font-size:.78em;padding:2px 7px;border-radius:999px;background:var(--secondary-background-color);color:var(--secondary-text-color)}.tagChoices{display:flex;gap:8px;flex-wrap:wrap}.tagChoices label{display:flex!important;flex-direction:row!important;align-items:center;gap:6px}.filterChip{margin:0 0 12px}.animalAvatar{width:42px;height:42px;object-fit:cover;border-radius:50%;flex:0 0 auto}.heroAvatar{width:76px;height:76px}.tileAvatar{width:44px;height:44px}.miniAvatar{width:30px;height:30px;border-radius:50%;object-fit:cover;flex:0 0 auto}.profileField{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;border:1px solid var(--divider-color);border-radius:10px;padding:12px}.profileField>legend{grid-column:1/-1}.profileField>.profilePreview{width:74px;height:74px;object-fit:cover;border-radius:12px}.profileField>.speciesEmoji,.profileField>ha-icon{width:74px;height:74px;display:grid;place-items:center;font-size:48px}.animalChecks080 label{align-items:center}.weightStepper080{display:grid;grid-template-columns:auto auto minmax(90px,1fr) auto auto;gap:5px}.weightStepper080 button{padding:8px 10px;white-space:nowrap}.reminderChronicle{display:flex!important;flex-direction:row!important;align-items:center;gap:8px}.weightTransition{margin-bottom:2px}
@media(max-width:650px){.weightStepper080{grid-template-columns:1fr 1fr}.weightStepper080 input{grid-column:1/-1;grid-row:1}.weightStepper080 button{font-size:.9em}.profileField{grid-template-columns:auto 1fr}.profileField>button{grid-column:1/-1}.heroAvatar{width:64px;height:64px}}
`;
const AH080Render=AH080.render;
AH080.render=function(){AH080Render.call(this);this.shadowRoot.innerHTML+=`<style>${AH080_CSS}</style>`};
