 saveExecution(f,o){const x=this.occ(o.occurrence_id),k=x.task_kind||"reminder",p={occurrence_id:x.id};for(const z of["performed_at","deviation_reason","notes"])if(o[z])p[z]=o[z];if(k==="weight")Object.assign(p,{weight:Number(o.weight),weight_unit:o.weight_unit});if(k==="medication"){for(const z of["medication_name","dose_unit","route"])if(o[z])p[z]=o[z];if(o.dose)p.dose=Number(o.dose)}if(k==="vaccination"){p.vaccination_targets=[...f.querySelectorAll('[name="vaccination_targets"]:checked')].map(y=>y.value);for(const z of["custom_vaccination_target","vaccine_name","antigen","dose_unit","route","batch_number"])if(o[z])p[z]=o[z];if(o.dose)p.dose=Number(o.dose)}if(k==="health_check"){p.check_result=o.check_result;if(o.check_result==="symptom")for(const z of["symptom","custom_symptom","severity"])if(o[z])p[z]=o[z]}if(k==="care")for(const z of["care_action","outcome"])if(o[z])p[z]=o[z];if(k==="veterinary_visit")for(const z of["visit_reason","provider","diagnosis"])if(o[z])p[z]=o[z];return this.svc(S[k],p,true)}
 saveResolution(o){return this.svc(o.resolution==="skip"?"skip_task_occurrence":"cancel_task_occurrence",{occurrence_id:o.occurrence_id,...(o.notes?{notes:o.notes}:{})},true)}
 syncTask(f){if(!f)return;const general=f.elements.task_scope.value==="general",kind=f.elements.task_kind;kind.disabled=general;if(general)kind.value="reminder";for(const s of f.querySelectorAll("[data-kind]")){s.hidden=s.dataset.kind!==kind.value;for(const x of s.querySelectorAll("input,select,textarea"))x.disabled=s.hidden}const a=f.querySelector("[data-animals]");if(a)a.hidden=general;this.custom(f,"planned_vaccination_targets","planned_custom_vaccination_target")}
 syncExec(f){if(!f)return;const hs=f.querySelector("[data-health]");if(hs){hs.hidden=f.elements.check_result?.value!=="symptom";for(const x of hs.querySelectorAll("input,select"))x.disabled=hs.hidden}this.custom(f,"vaccination_targets","custom_vaccination_target");const cs=f.querySelector('[name="custom_symptom"]');if(cs){const on=f.elements.symptom?.value==="other";cs.hidden=!on;cs.disabled=!on;cs.required=on}}
 custom(f,checks,name){const x=f.querySelector(`[name="${name}"]`);if(!x)return;const on=[...f.querySelectorAll(`[name="${checks}"]:checked`)].some(y=>y.value==="other");x.hidden=!on;x.disabled=!on;x.required=on}
 render(){this.shadowRoot.innerHTML=`<style>${CSS}</style>${this.body()}`;if(this.modal?.type==="create-task")this.syncTask(this.shadowRoot.querySelector("form"));if(this.modal?.type==="execute")this.syncExec(this.shadowRoot.querySelector("form"))}
 body(){if(!this.d)return`<main class="center">${this.err?`<ha-icon icon="mdi:alert-circle"></ha-icon><p>${esc(this.err)}</p><button data-action="refresh">${this.t("retry")}</button>`:`<ha-icon icon="mdi:paw"></ha-icon><p>${this.t("loading")}</p>`}</main>`;return`${this.d.version!==V?`<div class="warn">${this.t("version")}</div>`:""}<header><b><ha-icon icon="mdi:paw"></ha-icon> Animal Health</b><nav>${[["overview","mdi:view-dashboard"],["animals","mdi:paw"],["tasks","mdi:clipboard-check"],["calendar","mdi:calendar"],["timeline","mdi:timeline-clock"]].map(([v,i])=>`<button data-view="${v}" class="${this.view===v?"on":""}"><ha-icon icon="${i}"></ha-icon><span>${this.t(v)}</span></button>`).join("")}</nav><button data-action="refresh"><ha-icon icon="mdi:refresh"></ha-icon></button></header><main>${this.page()}</main>${this.modalHtml()}`}
 page(){return this.view==="overview"?this.overview():this.view==="animals"?this.animals():this.view==="tasks"?this.tasks():this.view==="calendar"?this.calendar():this.view==="timeline"?this.timeline():this.animalDetail()}
 heading(k,action=""){return`<div class="heading"><h1>${this.t(k)}</h1><div class="actions"><label class="search"><ha-icon icon="mdi:magnify"></ha-icon><input data-filter value="${esc(this.filter)}" placeholder="${this.t("search")}"></label>${action}</div></div>`}
 quick(id=""){return`<div class="quick"><button data-action="create-animal"><ha-icon icon="mdi:plus-circle-outline"></ha-icon>${this.t("createAnimal")}</button><button data-action="create-task"><ha-icon icon="mdi:clipboard-plus"></ha-icon>${this.t("createTask")}</button><button data-action="record-weight" data-id="${id}"><ha-icon icon="mdi:scale"></ha-icon>${this.t("recordWeight")}</button><button data-action="record-symptom" data-id="${id}"><ha-icon icon="mdi:alert-plus"></ha-icon>${this.t("recordSymptom")}</button></div>`}
 stat(i,n,k,b=""){return`<div class="stat ${b}"><ha-icon icon="${i}"></ha-icon><div><strong>${esc(n)}</strong><span>${this.t(k)}</span></div></div>`}
 overview(){const s=this.d.summary,hot=this.d.occurrences.filter(x=>x.is_overdue||x.is_today).slice(0,12);return`${this.heading("overview")}${this.quick()}<section class="stats">${this.stat("mdi:paw",s.active_animals,"activeAnimals")}${this.stat("mdi:alert",s.overdue_tasks,"overdue","bad")}${this.stat("mdi:calendar-today",s.today_tasks,"dueToday")}${this.stat("mdi:clipboard-clock",s.pending_tasks,"openTasks")}</section><section class="cols"><article class="card"><h2>${this.t("dueToday")}</h2>${this.rows(hot)}</article><article class="card"><h2>${this.t("recent")}</h2>${this.d.events.slice(0,10).map(x=>this.eventRow(x)).join("")||this.empty("noEvents")}</article></section>`}
 animals(){const q=this.filter.toLowerCase(),a=this.d.animals.filter(x=>!q||[x.name,x.species,x.breed,x.status,x.id].some(y=>String(y||"").toLowerCase().includes(q)));return`${this.heading("animals",`<button class="primary" data-action="create-animal"><ha-icon icon="mdi:plus-circle-outline"></ha-icon>${this.t("createAnimal")}</button>`)}<section class="grid">${a.map(x=>this.animalCard(x)).join("")||this.empty("noAnimals")}</section>`}
 animalCard(a){const w=a.latest_weight,n=this.d.occurrences.find(x=>x.animal_id===a.id&&x.status==="pending");return`<article class="animal ${a.is_archived?"muted":""}"><button class="animalHead" data-action="animal-detail" data-id="${a.id}"><ha-icon icon="mdi:paw"></ha-icon><div><h3>${esc(a.name)}</h3><span>${esc(a.species)}${a.breed?` · ${esc(a.breed)}`:""}</span></div><b>${this.l(a.status)}</b></button><div class="animalMeta"><span>${this.t("currentWeight")}<b>${w?`${this.num(w.original_value)} ${w.original_unit}`:"–"}</b></span><span>${this.t("upcoming")}<b>${n?esc(n.task_title):"–"}</b></span></div></article>`}
