Object.assign(T,{
 statusEffectiveAt012:["Status gültig ab / geändert am","Status effective / changed at"],
 statusDateHint012:["Vergangenheit oder jetzt: Status wird direkt mit diesem Zeitpunkt dokumentiert. Zukunft: Status bleibt unverändert und wird erst nach einer späteren Bestätigung übernommen.","Past or now: the status is recorded immediately with this timestamp. Future: the current status remains until the scheduled change is later confirmed."],
 statusChangeScheduled012:["Statusänderung geplant","Status change scheduled"],
 statusChangeDue012:["Statusänderung fällig","Status change due"],
 statusChangeConfirm012:["Wie geplant bestätigen","Confirm as planned"],
 statusChangeOtherTime012:["Anderer Zeitpunkt","Different time"],
 statusChangeCancel012:["Statusänderung abbrechen","Cancel status change"],
 statusChangeAlternative012:["Anderen Zeitpunkt festlegen","Set different time"],
 statusChangeResolution012:["Was soll mit dem neuen Zeitpunkt geschehen?","What should happen at the new time?"],
 statusChangeConfirmOther012:["Als tatsächlichen Zeitpunkt bestätigen","Confirm as actual time"],
 statusChangeReschedule012:["Neu planen und später erinnern","Reschedule and remind later"],
 plannedStatusChanges012:["Geplante Statusänderungen","Scheduled status changes"],
 statusChangeConfirmed012:["Statusänderung bestätigt","Status change confirmed"],
 statusChangeCancelled012:["Statusänderung abgebrochen","Status change cancelled"]
});
const AH012Status=AnimalHealthPanel.prototype;
const AH012StatusBase={
 form:AH012Status.form,
 saveStatus:AH012Status.saveStatus,
 dynamicRelevantCard095:AH012Status.dynamicRelevantCard095,
 animalDetail:AH012Status.animalDetail,
 handleClick:AH012Status.handleClick,
 handleSubmit:AH012Status.handleSubmit,
 render:AH012Status.render
};
AH012Status.statusChangeById012=function(id){return(this.v0912?.status_changes||[]).find(item=>String(item.id)===String(id))||null};
AH012Status.statusForm012=function(){const animal=this.animal(this.modal?.animalId),now=this.nowFields0817?this.nowFields0817():{date:this.d?.today||"",time:""};if(!animal)return this.empty("noAnimals");return`<h2>${this.t("changeStatus")}</h2><form data-form="status"><input type="hidden" name="animal_id" value="${esc(animal.id)}">${this.sel("status","status",this.c.animal_statuses,animal.status,"required")}<label><span>${this.t("statusEffectiveAt012")}</span><input type="datetime-local" name="effective_at" value="${esc(`${now.date}T${now.time}`)}" required><small>${this.t("statusDateHint012")}</small></label><label class="wide"><span>${this.t("notes")}</span><textarea name="notes" rows="2"></textarea></label>${this.buttons()}</form>`};
AH012Status.statusAlternativeForm012=function(){const change=this.statusChangeById012(this.modal?.changeId);if(!change)return this.empty("noTasks");const local=String(change.planned_for||"").slice(0,16);return`<h2>${this.t("statusChangeAlternative012")}</h2><form data-form="status-change-alternative-012"><input type="hidden" name="change_id" value="${esc(change.id)}"><p class="wide"><b>${esc(change.animal_name)}</b> → ${esc(this.l(change.target_status))}</p><label><span>${this.t("statusEffectiveAt012")}</span><input type="datetime-local" name="effective_at" value="${esc(local)}" required></label><label><span>${this.t("statusChangeResolution012")}</span><select name="resolution"><option value="confirm">${this.t("statusChangeConfirmOther012")}</option><option value="reschedule">${this.t("statusChangeReschedule012")}</option></select></label><div class="buttons wide"><button type="button" data-action="close">${this.t("close")}</button><button type="submit" class="primary">${this.t("save")}</button></div></form>`};
AH012Status.form=function(){if(this.modal?.type==="animal-status")return this.statusForm012();if(this.modal?.type==="status-change-alternative-012")return this.statusAlternativeForm012();return AH012StatusBase.form.call(this)};
AH012Status.saveStatus=async function(values){const result=await this.ws(`${D}/v0912/status_change/save`,{animal_id:values.animal_id,status:values.status,effective_at:values.effective_at,...(values.notes?{notes:values.notes}:{})});if(result?.scheduled)this.notify(this.t("statusChangeScheduled012"));return result};
AH012Status.statusChangeRow012=function(change,compact=false){const due=Boolean(change.is_due),when=this.fmt(change.planned_for,true),actions=due?`<div class="statusChangeActions012"><button class="primary" data-action="status-change-confirm-012" data-id="${esc(change.id)}">${this.t("statusChangeConfirm012")}</button><button data-action="status-change-alternative-012" data-id="${esc(change.id)}">${this.t("statusChangeOtherTime012")}</button><button data-action="status-change-cancel-012" data-id="${esc(change.id)}" title="${this.t("statusChangeCancel012")}"><ha-icon icon="mdi:close-circle-outline"></ha-icon></button></div>`:`<div class="statusChangeActions012"><button data-action="status-change-alternative-012" data-id="${esc(change.id)}"><ha-icon icon="mdi:calendar-edit"></ha-icon>${this.t("statusChangeOtherTime012")}</button><button data-action="status-change-cancel-012" data-id="${esc(change.id)}" title="${this.t("statusChangeCancel012")}"><ha-icon icon="mdi:close-circle-outline"></ha-icon></button></div>`;return`<div class="statusChangeRow012 ${due?"due012":"scheduled012"}"><ha-icon icon="${due?"mdi:alert-circle-outline":"mdi:calendar-clock-outline"}"></ha-icon><div><b>${esc(change.animal_name)} → ${esc(this.l(change.target_status))}</b><span>${due?this.t("statusChangeDue012"):this.t("statusChangeScheduled012")} · ${when}</span>${change.notes?`<small>${esc(change.notes)}</small>`:""}</div>${actions}</div>`};
AH012Status.dynamicRelevantCard095=function(){let html=AH012StatusBase.dynamicRelevantCard095.call(this),due=(this.v0912?.status_changes||[]).filter(item=>item.is_due);if(!due.length)return html;const group=`<div class="relevantGroup095 statusChangesDue012"><div class="relevantGroupHead095"><h3>${this.t("statusChangeDue012")}</h3><span>${due.length}</span></div>${due.map(item=>this.statusChangeRow012(item,true)).join("")}</div>`;return html.replace(/<\/section>\s*$/,`${group}</section>`)};
AH012Status.animalStatusCard012=function(animalId){const items=(this.v0912?.status_changes||[]).filter(item=>String(item.animal_id)===String(animalId));if(!items.length)return"";return`<section class="card statusChangesCard012"><h2>${this.t("plannedStatusChanges012")}</h2>${items.map(item=>this.statusChangeRow012(item)).join("")}</section>`};
AH012Status.animalDetail=function(){let html=AH012StatusBase.animalDetail.call(this),animal=this.detail?.animal;if(!animal)return html;const card=this.animalStatusCard012(animal.id);if(!card)return html;const marker=`<section class="card"><h2>${this.t("timeline")}</h2>`;return html.includes(marker)?html.replace(marker,card+marker):html+card};
AH012Status.resolveStatusChange012=async function(id,action,effectiveAt=""){const payload={change_id:id,action,...(effectiveAt?{effective_at:effectiveAt}:{})},result=await this.ws(`${D}/v0912/status_change/resolve`,payload);await this.loadV0912();await this.load();return result};
AH012Status.handleClick=async function(event){const button=event.composedPath().find(node=>node?.dataset?.action),action=button?.dataset?.action,id=String(button?.dataset?.id||"");if(action==="status-change-confirm-012"){try{await this.resolveStatusChange012(id,"confirm");this.notify(this.t("statusChangeConfirmed012"))}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return}if(action==="status-change-alternative-012"){this.modal={type:"status-change-alternative-012",changeId:id};this.render();return}if(action==="status-change-cancel-012"){try{await this.resolveStatusChange012(id,"cancel");this.notify(this.t("statusChangeCancelled012"))}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return}return AH012StatusBase.handleClick.call(this,event)};
AH012Status.handleSubmit=async function(event){const form=event.composedPath().find(node=>node?.tagName==="FORM");if(form?.dataset.form!=="status-change-alternative-012")return AH012StatusBase.handleSubmit.call(this,event);event.preventDefault();const values=data(form);try{this.busy=true;this.render();await this.ws(`${D}/v0912/status_change/resolve`,{change_id:values.change_id,action:values.resolution,effective_at:values.effective_at});this.busy=false;this.modal=null;await this.load();this.notify(this.t(values.resolution==="confirm"?"statusChangeConfirmed012":"statusChangeScheduled012"))}catch(error){this.busy=false;this.notify(`${this.t("failed")}: ${error?.message||error}`,true);this.render()}};
AH012Status.render=function(){AH012StatusBase.render.call(this);this.shadowRoot.innerHTML+=`<style>.statusChangeRow012{display:grid;grid-template-columns:auto 1fr auto;gap:9px;align-items:center;padding:9px;border-radius:9px;background:var(--secondary-background-color);margin:5px 0}.statusChangeRow012>ha-icon{color:var(--primary-color)}.statusChangeRow012.due012>ha-icon{color:var(--warning-color,#e6a700)}.statusChangeRow012>div:nth-child(2){display:flex;flex-direction:column;gap:2px}.statusChangeRow012 span,.statusChangeRow012 small{color:var(--secondary-text-color)}.statusChangeActions012{display:flex;gap:5px;align-items:center}.statusChangeActions012 button{white-space:nowrap}.statusChangesDue012 .statusChangeRow012{background:color-mix(in srgb,var(--warning-color,#e6a700) 10%,var(--card-background-color))}@media(max-width:650px){.statusChangeRow012{grid-template-columns:auto 1fr}.statusChangeActions012{grid-column:1/-1;justify-content:flex-end;flex-wrap:wrap}}</style>`};
