AH027.settingSections027=function(){return[
 ["general","mdi:tune-variant","settingsGeneral027","settingsGeneralHint027"],
 ["master","mdi:paw","settingsMaster027","settingsMasterHint027"],
 ["medications","mdi:pill","settingsMedication027","settingsMedicationHint027"],
 ["tasks","mdi:calendar-check-outline","settingsTasks027","settingsTasksHint027"],
 ["ai","mdi:creation-outline","settingsAi027","settingsAiHint027"],
 ["data","mdi:database-outline","settingsData027","settingsDataHint027"],
 ["system","mdi:cog-outline","settingsSystem027","settingsSystemHint027"],
 ["danger","mdi:alert-outline","settingsDanger027","settingsDangerHint027"]
]};
AH027.settingsLanding027=function(){return`${this.heading("settingsOverview027")}<section class="settingsGrid027">${this.settingSections027().map(([id,icon,title,hint])=>`<button type="button" class="settingsNav027 ${id==="danger"?"dangerNav027":""}" data-action="settings-section-027" data-section="${id}"><ha-icon icon="${icon}"></ha-icon><span><b>${this.t(title)}</b><small>${this.t(hint)}</small></span><ha-icon icon="mdi:chevron-right"></ha-icon></button>`).join("")}</section>`};
AH027.classifySettingCard027=function(node){const cls=String(node.className||""),text=String(node.textContent||"").toLocaleLowerCase();if(/medication|treatment|catalog/i.test(cls)||/(medikament|medicine|produkt|product|behandlung|treatment|swissmedic)/i.test(text))return"medications";if(/master|grouporder|symptom/i.test(cls)||/(tiergruppe|animal group|stammdaten|master data|rasse|breed|symptom|eintragsart|entry type)/i.test(text))return"master";if(/(aufgabe|task|kalender|calendar|planung|planning)/i.test(text))return"tasks";if(/(\bki\b|\bai\b|sprache|speech)/i.test(text))return"ai";if(/(export|backup|dokument|document|anhang|attachment|daten|data)/i.test(text))return"data";if(/(diagnos|system|integration|home assistant|technisch|technical)/i.test(text))return"system";if(/(zurücksetzen|reset|löschen|delete|test|gefahr|danger)/i.test(text))return"danger";return"general"};
AH027.legacySettingsBySection027=function(section){const template=document.createElement("template");template.innerHTML=AH027Base.settingsPage081.call(this);const cards=[...template.content.querySelectorAll("section.card")].filter(node=>!node.parentElement?.closest?.("section.card"));return cards.filter(card=>this.classifySettingCard027(card)===section).map(card=>card.outerHTML).join("")};
AH027.settingsBack027=function(section){const entry=this.settingSections027().find(item=>item[0]===section);return`<div class="settingsSubHead027"><button type="button" data-action="settings-back-027" title="${esc(this.t("backSettings027"))}"><ha-icon icon="mdi:arrow-left"></ha-icon></button><div><h1>${this.t(entry?.[2]||"settingsOverview027")}</h1>${entry?.[3]?`<p>${this.t(entry[3])}</p>`:""}</div></div>`};
AH027.productManager027=function(kind){const title={vaccination:"vaccineDatabase027",supplement:"supplementDatabase027",feed:"feedDatabase027"}[kind],items=(this.v0927?.products||[]).filter(item=>item.kind===kind),edit=this.productEdit027?.kind===kind?this.productEdit027:null,routes=this.c?.administration_routes||[];return`<section class="card productManager027"><h2>${this.t(title)}</h2><p>${this.t("productDatabaseHint027")}</p><form data-form="v0927-product" class="productForm027"><input type="hidden" name="kind" value="${kind}">${edit?.id?`<input type="hidden" name="item_id" value="${esc(edit.id)}">`:""}<label><span>${this.t("name")}</span><input name="name" value="${esc(edit?.name||"")}" required></label><label><span>${this.t("activeIngredient013")}</span><input name="active_ingredient" value="${esc(edit?.active_ingredient||"")}"></label><label><span>${this.t("concentration013")}</span><input name="concentration" value="${esc(edit?.concentration||"")}"></label><label><span>${this.t("dosageForm013")}</span><input name="dosage_form" value="${esc(edit?.dosage_form||"")}"></label><label><span>${this.t("productSpecies027")}</span><input name="target_species" value="${esc((edit?.target_species||[]).join(", "))}"></label><label><span>${this.t("productTargets027")}</span><input name="targets" value="${esc((edit?.targets||[]).join(", "))}"></label><label><span>${this.t("defaultRoute0817")}</span><select name="default_route"><option value="">–</option>${routes.map(route=>`<option value="${esc(route)}" ${route===edit?.default_route?"selected":""}>${esc(this.l(route))}</option>`).join("")}</select></label><div class="buttons">${edit?`<button type="button" data-action="product-edit-cancel-027">${this.t("cancel")}</button>`:""}<button class="primary" type="submit"><ha-icon icon="mdi:content-save-outline"></ha-icon>${this.t(edit?"save":"productAdd027")}</button></div></form><div class="productList027">${items.map(item=>`<div class="productRow027 ${item.is_hidden?"hidden027":""}"><span><b>${esc(item.name)}</b><small>${[item.is_custom?this.t("manual027"):this.t("official027"),item.active_ingredient,item.concentration,(item.targets||[]).map(target=>this.l(target)).join(", ")].filter(Boolean).map(esc).join(" · ")}</small></span><div><button type="button" data-action="product-edit-027" data-id="${esc(item.id)}" title="${esc(this.t("edit"))}"><ha-icon icon="mdi:pencil-outline"></ha-icon></button><button type="button" data-action="product-hide-027" data-id="${esc(item.id)}" data-hidden="${item.is_hidden?"0":"1"}" title="${esc(this.t(item.is_hidden?"productShow027":"productHide027"))}"><ha-icon icon="mdi:${item.is_hidden?"eye-off-outline":"eye-outline"}"></ha-icon></button>${!item.is_custom&&(item.is_modified||item.is_hidden)?`<button type="button" data-action="product-reset-027" data-id="${esc(item.id)}" title="${esc(this.t("resetOriginal024"))}"><ha-icon icon="mdi:restore"></ha-icon></button>`:""}</div></div>`).join("")||this.empty("noEvents")}</div></section>`};
AH027.settingsPage081=function(){const section=this.settingsSection027;if(!section)return this.settingsLanding027();let content=this.legacySettingsBySection027(section);if(section==="medications")content+=this.productManager027("vaccination")+this.productManager027("supplement")+this.productManager027("feed");return`${this.settingsBack027(section)}<div class="settingsSection027">${content||`<section class="card"><p>${this.t("settingsEmpty027")}</p></section>`}</div>`};

AH027.sig027=function(value){const number=Number(value);if(!Number.isFinite(number))return"";return new Intl.NumberFormat(this.lang()?"en-GB":"de-CH",{maximumSignificantDigits:3}).format(number)};
AH027.gabeTypeForEvent027=function(event){const direct=event?.data?.gabe_type;if(this.gabeKinds027().includes(direct))return direct;if(event?.event_type==="vaccination")return"vaccination";if(event?.event_type==="medication")return event?.data?.product_type==="supplement"?"supplement":"medication";if(event?.event_type==="care"&&event?.data?.component_type==="feed")return"feed";return null};
AH027.taskTitleExtra027=function(event,product){const execution=event?.data?.task_execution||{},title=String(execution.task_title||this.task?.(event?.task_id)?.title||"").trim();if(!title)return"";const clean=value=>String(value||"").toLocaleLowerCase().replace(/\b(geben|gabe|verabreichen|medikament|impfung|entwurmung|administer|administration|medication|vaccination|deworming)\b/g," ").replace(/[^a-z0-9äöüß]+/gi," ").trim(),task=clean(title),prod=clean(product);if(!task||prod.includes(task)||task.includes(prod))return"";return title};
AH027.activeSummary027=function(event){const amounts=Array.isArray(event?.data?.active_amounts)?event.data.active_amounts:[],parts=[];for(const item of amounts){const amount=item.amount_mg!=null?`${this.sig027(item.amount_mg)} mg`:item.amount!=null?`${this.sig027(item.amount)} ${item.unit||""}`:"";if(amount)parts.push(`${amount}${item.name?` ${item.name}`:""}`);if(item.mg_per_kg!=null)parts.push(`${this.sig027(item.mg_per_kg)} mg/kg KG`)}return parts};
AH027.eventCompact0817=function(event){const type=this.gabeTypeForEvent027(event);if(!type)return AH027Base.eventCompact0817.call(this,event);const snapshot=event.data?.medication_snapshot||event.data?.product_snapshot||{},product=snapshot.name||snapshot.product_name||event.data?.product_name||event.data?.medication_name||event.title||"",dose=event.value!=null?`${this.num(event.value)} ${this.l(event.unit||"")}`:"",route=event.data?.route?this.l(event.data.route):"",task=Boolean(event.task_id||event.data?.gabe_source==="task"||event.data?.task_execution),extraTitle=this.taskTitleExtra027(event,product),parts=this.activeSummary027(event);if(route)parts.push(route);if(extraTitle)parts.push(extraTitle);const typeBadge=type!=="medication"?`<span class="gabeKindBadge027">${esc(this.gabeKindLabel027(type))}</span>`:"",taskIcon=task?`<ha-icon class="taskSource027" icon="mdi:clipboard-check-outline" title="${esc(this.t("fromTask027"))}" aria-label="${esc(this.t("fromTask027"))}"></ha-icon>`:"",global=this.view!=="animal-detail",context=global&&event.animal_name?`<span class="gabeContext027">${esc(event.animal_name)}</span>`:"";return`<div class="row event eventOpen eventCompact0817 gabeCompact027 gabe-${type}" role="button" tabindex="0" data-action="event-detail" data-id="${esc(event.id)}"><ha-icon icon="${this.gabeKindIcon027(type)}"></ha-icon><div class="gabeContent027"><div class="gabeLine027">${dose?`<span class="gabeDose027">${esc(dose)}</span>`:""}<b>${esc(product)}</b>${typeBadge}${taskIcon}${parts.length?`<span class="gabeMeta027">· <i>${esc(parts.join(" · "))}</i></span>`:""}</div>${context}</div></div>`};
AH027.eventDetail=function(id){const event=this.eventById?.(id),html=AH027Base.eventDetail.call(this,id);if(!event||!(event.task_id||event.data?.gabe_source==="task"||event.data?.task_execution))return html;const execution=event.data?.task_execution||{},title=execution.task_title||this.task?.(event.task_id)?.title||"",scheduled=execution.scheduled_local||execution.scheduled_for||"",completed=execution.performed_local||execution.performed_at||event.occurred_at||"";return`${html}<section class="taskOriginDetail027"><h3><ha-icon icon="mdi:clipboard-check-outline"></ha-icon>${this.t("origin027")}: ${this.t("taskOrigin027")}</h3><dl>${title?`<div><dt>${this.t("taskOrigin027")}</dt><dd>${esc(title)}</dd></div>`:""}${scheduled?`<div><dt>${this.t("scheduled027")}</dt><dd>${esc(String(scheduled))}</dd></div>`:""}${completed?`<div><dt>${this.t("completed027")}</dt><dd>${esc(String(completed))}</dd></div>`:""}${event.task_id?`<div><dt>${this.t("taskId027")}</dt><dd>${esc(event.task_id)}</dd></div>`:""}</dl></section>`};
