const AH092=AnimalHealthPanel.prototype;
const AH092Base={overview:AH092.overview};
AH092.homeAnimalTile091=function(animal){
 const visual=this.animalVisual(animal,"homeAnimalAvatar091");
 return`<button class="homeAnimalTile091 homeAnimalTile092" data-action="animal-detail" data-id="${esc(animal.id)}" title="${esc(animal.name)}"><span class="homeAnimalVisualSlot092">${visual}</span><span class="homeAnimalName092">${esc(animal.name)}</span></button>`
};
AH092.homeAnimalGroup091=function(id,name,animals){if(!animals.length)return"";return`<div class="homeAnimalGroup091 homeAnimalNamedGroup092"><button class="homeAnimalGroupHead091" data-action="home-open-group-091" data-id="${esc(id)}"><span>${esc(name)}</span><small>${animals.length}</small><ha-icon icon="mdi:chevron-right"></ha-icon></button><div class="homeAnimalTiles091">${animals.map(animal=>this.homeAnimalTile091(animal)).join("")}</div></div>`};
AH092.homeFilterOption092=function(action,id,label,selected){return`<button class="homeFilterOption092 ${selected?"selected092 on":""}" data-action="${action}" data-id="${esc(id)}" aria-pressed="${selected?"true":"false"}"><span>${esc(label)}</span>${selected?'<ha-icon icon="mdi:check"></ha-icon>':""}</button>`};
AH092.homeAnimalOverview091=function(){
 const state=this.homeAnimalFilterState091(),all=(this.d?.animals||[]).filter(animal=>!animal.is_archived),matches=animal=>{
  if(state.group==="ungrouped"&&animal.group_id)return false;if(state.group!=="all"&&state.group!=="ungrouped"&&String(animal.group_id)!==String(state.group))return false;if(state.tag!=="all"&&!(animal.tag_ids||[]).map(String).includes(String(state.tag)))return false;
  if(state.query&&![animal.name,animal.species,animal.breed,animal.color,animal.group_name,...(animal.tags||[]).map(tag=>tag.name)].some(value=>String(value||"").toLocaleLowerCase().includes(state.query)))return false;return true
 },animals=all.filter(matches).sort((a,b)=>String(a.name||"").localeCompare(String(b.name||""),undefined,{sensitivity:"base"})),selectedGroup=state.group==="all"?this.t("allAnimals"):state.group==="ungrouped"?this.t("ungrouped"):state.groups.find(group=>String(group.id)===String(state.group))?.name||this.t("allAnimals"),selectedTag=state.tag==="all"?this.t("allTags"):`#${state.tags.find(tag=>String(tag.id)===String(state.tag))?.name||this.t("allTags")}`;
 const groupPanel=this.homeFilterPanel091==="group"?`<div class="homeFilterOptions091 homeFilterOptions092" role="group" aria-label="${esc(this.t("filterGroups091"))}">${this.homeFilterOption092("home-group-select-091","all",this.t("allAnimals"),state.group==="all")}${this.homeFilterOption092("home-group-select-091","ungrouped",this.t("ungrouped"),state.group==="ungrouped")}${state.groups.map(group=>this.homeFilterOption092("home-group-select-091",group.id,group.name,String(state.group)===String(group.id))).join("")}</div>`:"";
 const tagPanel=this.homeFilterPanel091==="tag"?`<div class="homeFilterOptions091 homeFilterOptions092" role="group" aria-label="${esc(this.t("filterTags091"))}">${this.homeFilterOption092("home-tag-select-091","all",this.t("allTags"),state.tag==="all")}${state.tags.map(tag=>this.homeFilterOption092("home-tag-select-091",tag.id,`#${tag.name}`,String(state.tag)===String(tag.id))).join("")}</div>`:"";
 const search=this.homeSearchOpen091?`<label class="homeAnimalSearch091"><ha-icon icon="mdi:magnify"></ha-icon><input data-home-search091 value="${esc(this.homeAnimalSearch091||"")}" placeholder="${this.t("search")}" autocomplete="off"></label>`:"";
 const ungrouped=animals.filter(animal=>!animal.group_id),sections=[];
 if((state.group==="all"||state.group==="ungrouped")&&ungrouped.length)sections.push(`<div class="homeUngroupedTiles092" aria-label="${esc(this.t("ungrouped"))}"><div class="homeAnimalTiles091">${ungrouped.map(animal=>this.homeAnimalTile091(animal)).join("")}</div></div>`);
 for(const group of state.groups){if(state.group!=="all"&&String(state.group)!==String(group.id))continue;const members=animals.filter(animal=>String(animal.group_id)===String(group.id));if(members.length)sections.push(this.homeAnimalGroup091(group.id,group.name,members))}
 const groupLabel=`${this.t("filterGroups091")}: ${selectedGroup}`,tagLabel=`${this.t("filterTags091")}: ${selectedTag}`,searchLabel=this.t("searchAnimals091");
 return`<section class="card homeAnimalsCard091 homeAnimalsCard092"><div class="homeAnimalsHead092"><h2>${this.t("animals")}</h2><div class="homeAnimalTools092" role="toolbar"><button class="homeIconTool092 ${state.group!=="all"||this.homeFilterPanel091==="group"?"on":""}" data-action="home-group-toggle-091" title="${esc(groupLabel)}" aria-label="${esc(groupLabel)}" aria-expanded="${this.homeFilterPanel091==="group"?"true":"false"}"><ha-icon icon="mdi:account-group-outline"></ha-icon></button><button class="homeIconTool092 ${state.tag!=="all"||this.homeFilterPanel091==="tag"?"on":""}" data-action="home-tag-toggle-091" title="${esc(tagLabel)}" aria-label="${esc(tagLabel)}" aria-expanded="${this.homeFilterPanel091==="tag"?"true":"false"}"><ha-icon icon="mdi:tag-multiple-outline"></ha-icon></button><button class="homeIconTool092 ${this.homeSearchOpen091||state.query?"on":""}" data-action="home-search-toggle-091" title="${esc(searchLabel)}" aria-label="${esc(searchLabel)}" aria-expanded="${this.homeSearchOpen091?"true":"false"}"><ha-icon icon="mdi:magnify"></ha-icon></button></div></div>${groupPanel}${tagPanel}${search}<div class="homeAnimalGroups091 homeAnimalGroups092">${sections.join("")||this.empty("noAnimals")}</div></section>`
};
AH092.overview=function(){
 let html=AH092Base.overview.call(this);
 if((this.overviewScope0816||"today")==="today")html=html.replace(/(<div class="actionNowHead actionNowHead0816"><div>)<small>[^<]*<\/small>/,"$1");
 return html+`<style>.homeAnimalsHead092{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px}.homeAnimalsHead092 h2,.quickCaptureHead091 h2,.actionNowHead0816 h2{margin:0!important;font-size:1.45rem!important;line-height:1.2!important;font-weight:700!important}.homeAnimalTools092{display:flex;align-items:center;gap:6px}.homeIconTool092{width:42px!important;height:42px!important;min-width:42px!important;padding:0!important;display:grid!important;place-items:center!important;border-radius:11px!important}.homeIconTool092.on{border-color:var(--primary-color)!important;box-shadow:inset 0 0 0 1px var(--primary-color);color:var(--primary-color)}.homeFilterOptions092{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:6px!important}.homeFilterOption092{display:grid!important;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:6px;text-align:left;justify-content:stretch!important}.homeFilterOption092 span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.homeFilterOption092.selected092{border-color:var(--primary-color)!important;box-shadow:inset 0 0 0 1px var(--primary-color);color:var(--primary-color);font-weight:700}.homeFilterOption092.selected092 ha-icon{width:20px;height:20px}.homeUngroupedTiles092{padding:2px 0 10px}.homeUngroupedTiles092+.homeAnimalNamedGroup092{border-top:1px solid var(--divider-color)}.homeAnimalTile092{display:grid!important;grid-template-rows:48px minmax(18px,auto)!important;justify-items:center!important;align-items:start!important;gap:5px!important}.homeAnimalVisualSlot092{width:48px;height:48px;display:grid;place-items:center;overflow:hidden;border-radius:9px}.homeAnimalVisualSlot092 .homeAnimalAvatar091{width:48px!important;height:48px!important;min-width:48px!important;margin:0!important;object-fit:cover}.homeAnimalVisualSlot092>ha-icon,.homeAnimalVisualSlot092 .speciesVisual,.homeAnimalVisualSlot092 .speciesBadge{margin:auto!important;align-self:center!important;justify-self:center!important}.homeAnimalName092{align-self:start;line-height:18px!important;min-height:18px}.homeAnimalGroups092{margin-top:6px}@media(max-width:420px){.homeAnimalsHead092{margin-bottom:8px}.homeIconTool092{width:40px!important;height:40px!important;min-width:40px!important}.homeAnimalTools092{gap:4px}.homeFilterOptions092{grid-template-columns:1fr 1fr}.homeAnimalTile092{grid-template-rows:44px minmax(18px,auto)!important}.homeAnimalVisualSlot092{width:44px;height:44px}.homeAnimalVisualSlot092 .homeAnimalAvatar091{width:44px!important;height:44px!important;min-width:44px!important}}</style>`
};
