Object.assign(T,{
 saveNewSymptom022:["Als neues eigenes Symptom speichern","Save as new custom symptom"],
 saveNewProduct022:["Als eigenes Produkt speichern","Save as custom product"]
});
const AH022=AnimalHealthPanel.prototype;
const AH022Base={
 eventDetail:AH022.eventDetail,
 treatmentBundle021:AH022.treatmentBundle021,
 medicationBatchBundle021:AH022.medicationBatchBundle021,
 renderSymptomSuggestions015:AH022.renderSymptomSuggestions015,
 renderMedicationSuggestions013:AH022.renderMedicationSuggestions013,
 handleClick:AH022.handleClick,
 render:AH022.render
};
AH022.rewriteAction022=function(html,action,icon,label){
 const expression=new RegExp(`<button([^>]*data-action="${action}"[^>]*)>[\\s\\S]*?<\\/button>`,"g"),text=this.t(label);
 return String(html||"").replace(expression,(_match,attrs)=>{const cleaned=String(attrs||"").replace(/\s+title="[^"]*"/g,"").replace(/\s+aria-label="[^"]*"/g,"");return`<button${cleaned} title="${esc(text)}" aria-label="${esc(text)}"><ha-icon icon="${icon}"></ha-icon><span class="actionLabel022">${esc(text)}</span></button>`})
};
AH022.removeCopyActions022=function(html){return String(html||"").replace(/<button[^>]*data-action="(?:med-copy-0817|treatment-copy-021|batch-copy-021)"[^>]*>[\s\S]*?<\/button>/g,"")};
AH022.responsiveEventActions022=function(html){
 let result=this.removeCopyActions022(html);
 result=this.rewriteAction022(result,"med-edit-0817","mdi:pencil-outline","editEntry0817");
 result=this.rewriteAction022(result,"med-repeat-0817","mdi:repeat","repeatMedication0817");
 result=this.rewriteAction022(result,"delete-event-013","mdi:delete-outline","deleteEntry013");
 result=this.rewriteAction022(result,"treatment-repeat-021","mdi:repeat","treatmentRepeat021");
 result=this.rewriteAction022(result,"batch-repeat-021","mdi:repeat","medicationGroupRepeat021");
 return result
};
AH022.eventDetail=function(id){return this.responsiveEventActions022(AH022Base.eventDetail.call(this,id))};
AH022.treatmentBundle021=function(event){return this.responsiveEventActions022(AH022Base.treatmentBundle021.call(this,event))};
AH022.medicationBatchBundle021=function(event){return this.responsiveEventActions022(AH022Base.medicationBatchBundle021.call(this,event))};
AH022.normalized022=function(value){return this.norm083?this.norm083(value):String(value||"").trim().toLocaleLowerCase()};
AH022.symptomExactKnown022=function(value){const clean=String(value||"").trim();if(!clean)return false;const norm=this.normalized022(clean);for(const item of this.symptomOptions015?.("")||[]){if(norm===this.normalized022(item.value)||norm===this.normalized022(item.label))return true}for(const item of this.v0915?.symptoms||[]){if(norm===this.normalized022(item.name))return true}return false};
AH022.productExactKnown022=function(value){const clean=String(value||"").trim();if(!clean)return false;const norm=this.normalized022(clean);for(const item of this.v0920?.catalog_products||[]){if([item.name,...(item.aliases||[])].some(candidate=>this.normalized022(candidate)===norm))return true}for(const item of this.v0913?.medications||[]){if(this.normalized022(item.name)===norm)return true}return false};
AH022.renderSymptomSuggestions015=function(input,open=true){AH022Base.renderSymptomSuggestions015.call(this,input,open);const menu=input?.form?.querySelector?.("[data-symptom-suggest015]"),clean=String(input?.value||"").trim();if(!menu||clean.length<2||this.symptomExactKnown022(clean))return;const create=`<button type="button" class="symptomOption015 createMaster022" data-action="symptom-save-new-022" data-value="${esc(clean)}"><ha-icon icon="mdi:plus-circle-outline"></ha-icon><span><b>${esc(clean)}</b><small>${esc(this.t("saveNewSymptom022"))}</small></span></button>`;if(menu.querySelector?.(".comboEmpty083"))menu.innerHTML=create;else menu.insertAdjacentHTML("beforeend",create);menu.hidden=!open};
AH022.renderMedicationSuggestions013=function(input,open=true){AH022Base.renderMedicationSuggestions013.call(this,input,open);const index=Number(input?.dataset?.medIndex0817),menu=input?.form?.querySelector?.(`[data-med-suggest013="${index}"]`),clean=String(input?.value||"").trim();if(!menu||clean.length<2||this.productExactKnown022(clean))return;const create=`<button type="button" class="medSuggestion013 createMaster022" data-action="product-save-new-022" data-index="${index}" data-value="${esc(clean)}"><ha-icon icon="mdi:plus-circle-outline"></ha-icon><span><b>${esc(clean)}</b><small>${esc(this.t("saveNewProduct022"))}</small></span></button>`;if(menu.querySelector?.(".comboEmpty083"))menu.innerHTML=create;else menu.insertAdjacentHTML("beforeend",create);menu.hidden=!open};
AH022.refreshSymptomChips022=function(){const chips=this.shadowRoot.querySelector(".symptomChips015");if(chips)chips.outerHTML=this.symptomChips015()};
AH022.addSymptomChoice015=function(value){const clean=String(value||"").trim();if(!clean)return;const draft=this.ensureSymptomDraft015(),key=this.normalized022(clean),exists=draft.selected.some(item=>this.normalized022(item)===key);if(!exists)draft.selected.push(clean);draft.query="";this.refreshSymptomChips022();const input=this.shadowRoot.querySelector("[data-symptom-search015]");if(input){input.value="";input.focus({preventScroll:true});const menu=input.form?.querySelector?.("[data-symptom-suggest015]");if(menu)menu.hidden=true}};
AH022.handleClick=async function(event){const button=event.composedPath().find(node=>node?.dataset?.action),action=button?.dataset?.action;if(["med-copy-0817","treatment-copy-021","batch-copy-021"].includes(action))return;if(action==="symptom-remove-015"){const index=Number(button.dataset.index),draft=this.ensureSymptomDraft015();if(Number.isInteger(index)&&index>=0&&index<draft.selected.length)draft.selected.splice(index,1);this.refreshSymptomChips022();return}if(action==="symptom-save-new-022"){const name=String(button.dataset.value||"").trim();if(!name)return;try{await this.ws(`${D}/v0915/symptom/save`,{name});await this.loadV0915();this.addSymptomChoice015(name);this.notify(this.t("symptomSaved015"))}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return}if(action==="product-save-new-022"){const name=String(button.dataset.value||"").trim(),index=Number(button.dataset.index),form=button.closest("form"),input=form?.querySelector?.(`[data-med-search013][data-med-index0817="${index}"]`),animalId=form?.elements?.animal_id?.value||this.medBatch0817?.animalId||"",animal=this.animal?.(animalId),speciesId=animal&&this.speciesId?this.speciesId(animal.species):"",state=this.medBatch0817?.items?.[index]||{};if(!name||!input)return;try{await this.ws(`${D}/v0913/medication/save`,{name,species_id:speciesId||"",default_unit:state.dose_unit||this.medicationUnit0817(name)||"dose",default_route:state.route||this.medicationRoute0817(name)||"",active_ingredient:"",concentration:"",dosage_form:""});await this.loadV0913();this.applyMedicationChoice013(input,name);this.notify(this.t("medicationSaved0817"))}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return}return AH022Base.handleClick.call(this,event)};
AH022.render=function(){AH022Base.render.call(this);this.shadowRoot.innerHTML+=`<style>
.eventActions0817 button,.eventActions021 button,.bundleActions021 button{display:inline-flex;align-items:center;justify-content:center;gap:6px}.eventActions0817 button ha-icon,.eventActions021 button ha-icon,.bundleActions021 button ha-icon{flex:0 0 auto}.actionLabel022{display:inline}.eventActions0817,.eventActions021,.bundleActions021{gap:6px}.createMaster022{display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:8px!important;border-top:1px solid var(--divider-color)!important}.createMaster022>span{display:flex;flex-direction:column;align-items:flex-start;gap:1px}.createMaster022 small{color:var(--secondary-text-color);font-size:.72rem}
:host([narrow]) .eventActions0817,:host([narrow]) .eventActions021,:host([narrow]) .bundleActions021{justify-content:flex-end!important;align-items:center!important;flex-wrap:wrap!important}:host([narrow]) .eventActions0817 button,:host([narrow]) .eventActions021 button,:host([narrow]) .bundleActions021 button{width:42px!important;height:42px!important;min-width:42px!important;max-width:42px!important;min-height:42px!important;padding:0!important;display:grid!important;place-items:center!important;flex:0 0 42px!important}:host([narrow]) .eventActions0817 button ha-icon,:host([narrow]) .eventActions021 button ha-icon,:host([narrow]) .bundleActions021 button ha-icon{width:22px!important;height:22px!important;margin:0!important}:host([narrow]) .actionLabel022{display:none!important}
@media(max-width:700px){.eventActions0817,.eventActions021,.bundleActions021{justify-content:flex-end!important;align-items:center!important;flex-wrap:wrap!important}.eventActions0817 button,.eventActions021 button,.bundleActions021 button{width:42px!important;height:42px!important;min-width:42px!important;max-width:42px!important;min-height:42px!important;padding:0!important;display:grid!important;place-items:center!important;flex:0 0 42px!important}.eventActions0817 button ha-icon,.eventActions021 button ha-icon,.bundleActions021 button ha-icon{width:22px!important;height:22px!important;margin:0!important}.actionLabel022{display:none!important}}
</style>`};
