Object.assign(T,{
 confirmationMode010:["Bestätigungsmodus","Confirmation mode"],
 confirmationRequired010:["Einzelbestätigung erforderlich","Individual confirmation required"],
 confirmationRoutine010:["Routine ohne Einzelbestätigung","Routine without individual confirmation"],
 confirmationHint010:["Bei Pflichtbestätigung bleibt eine offene Fälligkeit nach Ablauf des Zeitraums überfällig. Routinen werden danach als nicht einzeln dokumentiert abgeschlossen, ohne eine Durchführung zu behaupten.","Required confirmations remain overdue after their period ends. Routine items are then closed as not individually documented without claiming completion."],
 confirmationRequiredShort010:["Bestätigung erforderlich","Confirmation required"],
 confirmationRoutineShort010:["Routine","Routine"],
 notDocumented010:["Nicht einzeln dokumentiert","Not individually documented"],
 notDocumentedCount010:["nicht einzeln dokumentiert","not individually documented"],
 overdueOnly010:["Überfällig","Overdue"],
 dueThisWeek010:["Diese Woche fällig","Due this week"],
 dueThisMonth010:["Diesen Monat fällig","Due this month"],
 calendarNotDocumented010:["Nicht einzeln dokumentiert","Not individually documented"],
 calendarOverdue010:["Überfällig","Overdue"],
 confirmationSaved010:["Bestätigungsmodus gespeichert","Confirmation mode saved"]
});
L.not_documented=["Nicht einzeln dokumentiert","Not individually documented"];
T.overdueUnconfirmed097=["Überfällig","Overdue"];
T.calendarUnconfirmed097=["Nicht einzeln dokumentiert","Not individually documented"];
const AH010=AnimalHealthPanel.prototype;
const AH010Base={
 taskForm:AH010.taskForm,
 syncTask:AH010.syncTask,
 saveTask:AH010.saveTask,
 handleChange:AH010.handleChange,
 handleSubmit:AH010.handleSubmit,
 taskEditForm097:AH010.taskEditForm097,
 taskManagementRow097:AH010.taskManagementRow097,
 seriesPendingItem097:AH010.seriesPendingItem097,
 seriesRow097:AH010.seriesRow097,
 calendar:AH010.calendar,
 calendarState097:AH010.calendarState097,
 calendarIcon097:AH010.calendarIcon097,
 resolveCalendarOccurrence099:AH010.resolveCalendarOccurrence099,
 animalSeriesStatusRow097:AH010.animalSeriesStatusRow097,
 weekStart095:AH010.weekStart095,
 setWeekStart095:AH010.setWeekStart095,
 render:AH010.render
};
AH010.confirmationDefault010=function(kind){return["reminder","care"].includes(String(kind||"reminder"))?"routine":"required"};
AH010.confirmationMode010=function(task){const mode=String(task?.confirmation_mode||"required");return mode==="routine"?"routine":"required"};
AH010.confirmationField010=function(value="required",hidden=false){return`<label class="wide confirmationField010" data-confirmation-field010 ${hidden?"hidden":""}><span>${this.t("confirmationMode010")}</span><select name="confirmation_mode" data-confirmation-mode010 ${hidden?"disabled":""}><option value="required" ${value==="required"?"selected":""}>${this.t("confirmationRequired010")}</option><option value="routine" ${value==="routine"?"selected":""}>${this.t("confirmationRoutine010")}</option></select><small>${this.t("confirmationHint010")}</small></label>`};
AH010.taskForm=function(){let html=AH010Base.taskForm.call(this);if(html.includes('name="confirmation_mode"'))return html;return html.replace('<div class="buttons wide">',`${this.confirmationField010("required",false)}<div class="buttons wide">`)};
AH010.syncConfirmationMode010=function(form){const field=form?.querySelector?.("[data-confirmation-field010]"),select=form?.elements?.confirmation_mode;if(!field||!select)return;const recurring=form.elements.recurrence_type?.value!=="once",kind=form.elements.task_scope?.value==="general"?"reminder":form.elements.task_kind?.value||"reminder";field.hidden=!recurring;select.disabled=!recurring;if(!recurring){select.value="required";return}if(select.dataset.userSelected010!=="1")select.value=this.confirmationDefault010(kind)};
AH010.syncTask=function(form){AH010Base.syncTask.call(this,form);this.syncConfirmationMode010(form)};
AH010.findTasks010=function(value,seen=new Set()){if(!value||typeof value!=="object"||seen.has(value))return[];seen.add(value);if(Array.isArray(value.tasks))return value.tasks;if(value.task&&typeof value.task==="object")return[value.task];for(const key of["response","result","data"]){const found=this.findTasks010(value[key],seen);if(found.length)return found}return[]};
AH010.saveTask=async function(form,values){const result=await AH010Base.saveTask.call(this,form,values),recurring=values.recurrence_type!=="once",kind=values.task_scope==="general"?"reminder":values.task_kind||"reminder",desired=recurring?(values.confirmation_mode||this.confirmationDefault010(kind)):"required",defaultMode=recurring?this.confirmationDefault010(kind):"required";if(desired!==defaultMode){for(const task of this.findTasks010(result)){if(task?.id)await this.ws(`${D}/confirmation/mode/update`,{task_id:String(task.id),confirmation_mode:desired})}}return result};
AH010.weekStart095=function(){const backend=String(this.v081?.settings?.week_start||"");return["monday","tuesday","wednesday","thursday","friday","saturday","sunday"].includes(backend)?backend:AH010Base.weekStart095.call(this)};
AH010.setWeekStart095=function(value){AH010Base.setWeekStart095.call(this,value);if(this.v081){this.v081.settings=this.v081.settings||{};this.v081.settings.week_start=value}};
AH010.handleChange=function(event){const input=event.composedPath()[0],form=input?.form;if(input?.dataset&&"weekStart095" in input.dataset){const value=input.value;this.setWeekStart095(value);this.render();void this.ws(`${D}/confirmation/week_start/update`,{week_start:value}).catch(error=>this.notify(`${this.t("failed")}: ${error?.message||error}`,true));return}if(input?.dataset?.confirmationMode010!==undefined)input.dataset.userSelected010="1";AH010Base.handleChange.call(this,event);if(form?.dataset.form==="task"&&["task_kind","task_scope","recurrence_type","confirmation_mode"].includes(input.name))this.syncConfirmationMode010(form)};
AH010.taskEditForm097=function(task){let html=AH010Base.taskEditForm097.call(this,task);if(String(task.recurrence_type||"once")==="once")return html;return html.replace('<div class="buttons wide">',`${this.confirmationField010(this.confirmationMode010(task),false)}<div class="buttons wide">`)};
AH010.handleSubmit=async function(event){const form=event.composedPath().find(node=>node?.tagName==="FORM");if(form?.dataset.form!=="task-edit-097")return AH010Base.handleSubmit.call(this,event);event.preventDefault();const values=data(form),task=this.task(values.task_id),mode=values.recurrence_type==="once"?"required":values.confirmation_mode||this.confirmationMode010(task),payload={task_id:values.task_id,title:values.title,description:values.description||null,recurrence_type:values.recurrence_type,recurrence_interval:Number(values.recurrence_interval||1),start_date:values.start_date,...(values.end_date?{end_date:values.end_date}:{clear_end_date:true}),...(values.due_time?{due_time:values.due_time}:{clear_due_time:true})};this.busy=true;this.render();try{await this.svc("update_task",payload,true);if(mode!==this.confirmationMode010(task))await this.ws(`${D}/confirmation/mode/update`,{task_id:values.task_id,confirmation_mode:mode});this.busy=false;this.modal=null;await this.load();this.notify(this.t("done"))}catch(error){this.busy=false;this.notify(`${this.t("failed")}: ${error?.message||error}`,true);this.render()}};
AH010.taskManagementRow097=function(task){const recurring=String(task.recurrence_type||"once")!=="once",target=this.taskTarget097(task),recurrence=recurring?this.recurrenceLabel095(task):this.l("once"),mode=this.confirmationMode010(task),modeLabel=mode==="routine"?this.t("confirmationRoutineShort010"):this.t("confirmationRequiredShort010"),overdue=mode==="required"?Math.max(0,Number(task.overdue_count||0)):0,nextValue=task.next_pending_local||task.next_pending_at||"",next=nextValue?this.fmt(nextValue,true):"–",inactive=task.is_active===false,meta=[target,this.l(task.task_kind||"reminder"),recurrence,recurring?modeLabel:""].filter(Boolean).join(" · "),status=overdue?`<span class="taskBadge097 warning097">${overdue} ${this.t("overdueOnly010")}</span>`:inactive?`<span class="taskBadge097 inactive097">${this.t("taskInactive")}</span>`:`<span class="taskNext097">${this.t("nextDue095")}: ${next}</span>`;return`<article class="taskDefinition097 ${inactive?"inactive097":""} ${overdue?"overdue097":""}"><ha-icon icon="${I[task.task_kind]||I.reminder}"></ha-icon><div class="taskDefinitionMain097"><b>${esc(task.title)}</b><span>${esc(meta)}</span>${status}</div><div class="taskDefinitionActions097"><button data-action="edit-task-097" data-id="${esc(task.id)}" title="${esc(this.t("editTask097"))}" aria-label="${esc(this.t("editTask097"))}"><ha-icon icon="mdi:pencil-outline"></ha-icon></button><button class="${task.is_active?"":"on"}" data-action="toggle" data-id="${esc(task.id)}">${this.t(task.is_active?"deactivate":"activate")}</button></div></article>`};
AH010.periodBounds010=function(task,key){const day=this.utcDate0815(key);if(!day)return{start:key,end:key};const type=String(task?.recurrence_type||"once");if(type==="weekly"){const bounds=this.weekBounds095(day);return{start:this.dateKey0815(bounds.start),end:this.dateKey0815(bounds.end)}}if(type==="monthly")return{start:this.dateKey0815(new Date(Date.UTC(day.getUTCFullYear(),day.getUTCMonth(),1))),end:this.dateKey0815(new Date(Date.UTC(day.getUTCFullYear(),day.getUTCMonth()+1,0)))};return{start:key,end:key}};
AH010.periodState010=function(task,key,todayKey){const bounds=this.periodBounds010(task,key);if(bounds.end<todayKey)return"past";if(bounds.start<=todayKey&&todayKey<=bounds.end)return"current";return"future"};
AH010.currentBucket010=function(task){const type=String(task?.recurrence_type||"once");return type==="weekly"?"thisWeek":type==="monthly"?"thisMonth":"today"};
AH010.seriesPendingItem097=function(task,today,todayKey,thisWeek,nextWeekStart,nextWeekEnd,nextMonthEnd,summary){const occurrences=(this.d?.occurrences||[]).filter(item=>String(item.task_id)===String(task.id)),pending=occurrences.filter(item=>item.status==="pending").sort((a,b)=>this.occurrenceDate0816(a).localeCompare(this.occurrenceDate0816(b))),mode=this.confirmationMode010(task),overdue=mode==="required"?pending.filter(item=>this.periodState010(task,this.occurrenceDate0816(item),todayKey)==="past"):[];if(overdue.length){const occurrence=overdue[0],key=this.occurrenceDate0816(occurrence);return{bucket:"overdue",item:{task,key,occurrence,isOverdue:true,series097:true,state097:"overdue",missedCount:overdue.length}}}const current=pending.find(item=>this.periodState010(task,this.occurrenceDate0816(item),todayKey)==="current");if(current){const key=this.occurrenceDate0816(current);return{bucket:this.currentBucket010(task),item:{task,key,occurrence:current,isOverdue:false,series097:true,state097:"due",missedCount:0}}}const next=summary||null,key=next?.key||"";if(!key)return{bucket:"series",item:{task,key:"",occurrence:null,isOverdue:false,series097:true,state097:"planned",missedCount:0}};const day=this.utcDate0815(key);let bucket="series";if(day){if(day<=thisWeek.end)bucket="thisWeek";else if(day>=nextWeekStart&&day<=nextWeekEnd)bucket="nextWeek";else if(day.getUTCFullYear()===today.getUTCFullYear()&&day.getUTCMonth()===today.getUTCMonth())bucket="thisMonth";else if(day<=nextMonthEnd)bucket="nextMonth"}return{bucket,item:{...next,task,series097:true,state097:"planned",missedCount:0}}};
AH010.dueLabel010=function(task){const type=String(task?.recurrence_type||"once");return type==="weekly"?this.t("dueThisWeek010"):type==="monthly"?this.t("dueThisMonth010"):this.t("dueToday097")};
AH010.seriesRow097=function(item){const task=item.task,target=this.taskTarget097(task),recurrence=this.recurrenceLabel095(task),date=item.key?this.fmt(item.key):"",state=item.state097||"planned",statusText=state==="overdue"?`${item.missedCount||1} ${this.t("overdueOnly010")} · ${this.t("since097")} ${date}`:state==="due"?`${this.dueLabel010(task)}${task.due_time?` · ${esc(String(task.due_time).slice(0,5))}`:""}`:date?`${this.t("nextDue095")}: ${date}`:recurrence,canExecute=Boolean(item.occurrence&&(state==="overdue"||state==="due")),className=state==="overdue"?"overdue010":state==="due"?"due097":"planned097";return`<div class="nextTask seriesTask097 ${className}"><div class="nextTaskIcon"><ha-icon icon="${I[task.task_kind]||I.reminder}"></ha-icon></div><div class="nextTaskMain static0816"><b>${esc(task.title)}</b><span>${esc(target)} · ${esc(recurrence)} · ${statusText}</span></div>${canExecute?`<button class="primary compactExecute" data-action="execute" data-id="${esc(item.occurrence.id)}">${this.t("execute")}</button>`:""}</div>`};
AH010.calendarState097=function(task,key,todayKey){const occurrence=this.occurrenceForTaskDate0816(task.id,key),mode=this.confirmationMode010(task),period=this.periodState010(task,key,todayKey);if(occurrence?.status==="completed")return{key:"completed",label:this.t("calendarCompleted097"),occurrence,date:key,taskId:String(task.id)};if(["skipped","cancelled"].includes(occurrence?.status))return{key:"stopped",label:this.t("calendarStopped097"),occurrence,date:key,taskId:String(task.id)};if(occurrence?.status==="not_documented")return{key:"undocumented",label:this.t("calendarNotDocumented010"),occurrence,date:key,taskId:String(task.id)};if(occurrence?.status==="pending"){if(period==="past")return mode==="required"?{key:"overdue",label:this.t("calendarOverdue010"),occurrence,date:key,taskId:String(task.id)}:{key:"undocumented",label:this.t("calendarNotDocumented010"),occurrence,date:key,taskId:String(task.id)};if(period==="current")return{key:"due",label:this.t("calendarDue097"),occurrence,date:key,taskId:String(task.id)};return{key:"planned",label:this.t("calendarPlanned097"),occurrence,date:key,taskId:String(task.id)}}if(period==="past")return mode==="required"?{key:"overdue",label:this.t("calendarOverdue010"),occurrence:null,date:key,taskId:String(task.id)}:{key:"undocumented",label:this.t("calendarNotDocumented010"),occurrence:null,date:key,taskId:String(task.id)};if(period==="current")return{key:"due",label:this.t("calendarDue097"),occurrence:null,date:key,taskId:String(task.id)};return{key:"planned",label:this.t("calendarPlanned097"),occurrence:null,date:key,taskId:String(task.id)}};
