Object.assign(T,{
 treatmentRepeat021:["Behandlungsplan nochmals ausführen","Run treatment plan again"],
 treatmentCopy021:["Behandlungsplan kopieren","Copy treatment plan"],
 treatmentUnavailable021:["Der zugehörige Behandlungsplan ist nicht mehr aktiv verfügbar.","The related treatment plan is no longer actively available."],
 medicationGroup021:["Gemeinsame Medikamentengabe","Medication group"],
 medicationGroupCount021:["Gaben","administrations"],
 medicationGroupRepeat021:["Gruppe nochmals verabreichen","Administer group again"],
 medicationGroupCopy021:["Gruppe kopieren","Copy group"],
 treatmentStep021:["Behandlungsschritt","Treatment step"]
});
const AH021=AnimalHealthPanel.prototype;
const AH021Base={
 eventRow:AH021.eventRow,
 eventCompact0817:AH021.eventCompact0817,
 eventDetail:AH021.eventDetail,
 homeTimeline013:AH021.homeTimeline013,
 handleClick:AH021.handleClick,
 render:AH021.render
};
AH021.eventSource021=function(event){const source=this.eventList0817?this.eventList0817(event):(this.view==="animal-detail"?this.detail?.events:this.d?.events)||[];return this.effectiveEvents0817?this.effectiveEvents0817(source):source};
AH021.batchId021=function(event){return String(event?.data?.batch_id||"")};
AH021.batchMembers021=function(event,list=null){const id=this.batchId021(event);if(!id)return[];const source=list||this.eventSource021(event);return(source||[]).filter(item=>item?.event_type==="medication"&&this.batchId021(item)===id)};
AH021.isMedicationBatch021=function(event,list=null){if(event?.event_type!=="medication")return false;const members=this.batchMembers021(event,list);return members.length>1&&members.some(item=>String(item?.data?.entry_mode||"")==="batch")};
AH021.batchRepresentative021=function(event,list=null){const members=this.batchMembers021(event,list);return members.length?members[0]:null};
AH021.isMedicationBatchChild021=function(event,list=null){if(!this.isMedicationBatch021(event,list))return false;const representative=this.batchRepresentative021(event,list);return Boolean(representative&&String(representative.id)!==String(event.id))};
AH021.treatmentComponents021=function(event){let components=event?.data?.components||event?.data?.treatment_plan_components||event?.data?.task_execution?.planned?.treatment_plan_components||event?.data?.task_execution?.treatment_plan_components||[];if(!Array.isArray(components)||!components.length){const planId=this.treatmentPlanId020?.(event),plan=(this.v0918?.treatment_plans||this.v0912?.treatment_plans||[]).find(item=>String(item.id)===String(planId));components=plan?.components||[]}return Array.isArray(components)?components:[]};
AH021.componentSummary021=function(item){if(!item)return"";const name=String(item.name||"").trim();if(!name)return"";if(String(item.type||"")==="action")return name;const amount=item.dose!=null&&item.dose!==""?`${this.num(item.dose)} ${this.l(item.unit||"")}`:"";return[name,amount].filter(Boolean).join(" · ")};
AH021.eventSummary021=function(event){const amount=event?.value!=null?`${this.num(event.value)} ${this.l(event.unit||"")}`:"",title=this.eventTitle?this.eventTitle(event):event?.title||"";return[title,amount].filter(Boolean).join(" · ")};
AH021.bundleMeta021=function(event){const global=this.view!=="animal-detail";return[this.fmt(event.occurred_at,true),global?event.animal_name:""].filter(Boolean).join(" · ")};
AH021.rawCompact021=function(event){return AH020Base.eventCompact0817.call(this,event)};
AH021.expandedTreatmentSet021=function(){if(!(this.expandedTreatments021 instanceof Set))this.expandedTreatments021=new Set;return this.expandedTreatments021};
AH021.expandedMedicationBatchesSet021=function(){if(!(this.expandedMedicationBatches021 instanceof Set))this.expandedMedicationBatches021=new Set;return this.expandedMedicationBatches021};
AH021.treatmentBundle021=function(event){const list=this.eventSource021(event),children=this.treatmentChildren020?this.treatmentChildren020(event,list):[],components=this.treatmentComponents021(event),actions=components.filter(item=>String(item.type||"")==="action"),preview=(components.length?components.map(item=>this.componentSummary021(item)):children.map(item=>this.eventSummary021(item))).filter(Boolean),expanded=this.expandedTreatmentSet021().has(String(event.id)),label=this.t(expanded?"treatmentCollapse020":"treatmentExpand020"),childHtml=expanded?`<div class="bundleChildren021">${children.map(child=>`<div class="bundleChild021">${this.rawCompact021(child)}</div>`).join("")}${actions.map(step=>`<div class="row event eventCompact0817 bundleActionStep021"><ha-icon icon="mdi:hand-heart-outline"></ha-icon><div><b>${esc(step.name||this.t("treatmentStep021"))}</b>${step.instructions?`<span>${esc(step.instructions)}</span>`:""}</div></div>`).join("")}<div class="bundleActions021"><button type="button" data-action="treatment-copy-021" data-id="${esc(event.id)}"><ha-icon icon="mdi:content-copy"></ha-icon>${this.t("treatmentCopy021")}</button><button type="button" class="primary" data-action="treatment-repeat-021" data-id="${esc(event.id)}"><ha-icon icon="mdi:repeat"></ha-icon>${this.t("treatmentRepeat021")}</button></div></div>`:"";return`<div class="bundleGroup021 treatmentGroup021"><div class="row event eventCompact0817 bundleRow021 treatmentSummary021" role="button" tabindex="0" data-action="event-detail" data-id="${esc(event.id)}"><ha-icon icon="${I.treatment||"mdi:medical-bag"}"></ha-icon><div class="bundleText021"><b>${esc(event.title||this.t("treatment"))}</b><span>${esc(this.bundleMeta021(event))}</span>${preview.length?`<span class="bundlePreview021">${preview.map(item=>`<small>${esc(item)}</small>`).join("")}</span>`:""}</div><button type="button" class="bundleChevron021" data-action="toggle-treatment-021" data-id="${esc(event.id)}" title="${esc(label)}" aria-label="${esc(label)}"><ha-icon icon="mdi:chevron-${expanded?"up":"down"}"></ha-icon></button></div>${childHtml}</div>`};
AH021.medicationBatchBundle021=function(event){const list=this.eventSource021(event),members=this.batchMembers021(event,list),batchId=this.batchId021(event),expanded=this.expandedMedicationBatchesSet021().has(batchId),preview=members.map(item=>this.eventSummary021(item)).filter(Boolean),label=expanded?this.t("treatmentCollapse020"):this.t("treatmentExpand020"),childHtml=expanded?`<div class="bundleChildren021">${members.map(child=>`<div class="bundleChild021">${this.rawCompact021(child)}</div>`).join("")}<div class="bundleActions021"><button type="button" data-action="batch-copy-021" data-id="${esc(event.id)}"><ha-icon icon="mdi:content-copy"></ha-icon>${this.t("medicationGroupCopy021")}</button><button type="button" class="primary" data-action="batch-repeat-021" data-id="${esc(event.id)}"><ha-icon icon="mdi:repeat"></ha-icon>${this.t("medicationGroupRepeat021")}</button></div></div>`:"";return`<div class="bundleGroup021 medicationBatchGroup021"><div class="row event eventCompact0817 bundleRow021 medicationBatchSummary021" role="button" tabindex="0" data-action="toggle-med-batch-021" data-id="${esc(event.id)}"><ha-icon icon="mdi:pill-multiple"></ha-icon><div class="bundleText021"><b>${esc(this.t("medicationGroup021"))}</b><span>${esc(this.bundleMeta021(event))} · ${members.length} ${esc(this.t("medicationGroupCount021"))}</span>${preview.length?`<span class="bundlePreview021">${preview.map(item=>`<small>${esc(item)}</small>`).join("")}</span>`:""}</div><button type="button" class="bundleChevron021" data-action="toggle-med-batch-021" data-id="${esc(event.id)}" title="${esc(label)}" aria-label="${esc(label)}"><ha-icon icon="mdi:chevron-${expanded?"up":"down"}"></ha-icon></button></div>${childHtml}</div>`};
AH021.visibleTimelineEvents021=function(source){const list=source||[];return list.filter(event=>{if(this.treatmentSummaryForChild020?.(event,list))return false;if(this.isMedicationBatchChild021(event,list))return false;return true})};
AH021.eventCompact0817=function(event){const list=this.eventSource021(event);if(this.treatmentSummaryForChild020?.(event,list))return"";if(event?.event_type==="treatment"&&(this.treatmentPlanId020?.(event)!=null||this.treatmentChildren020?.(event,list)?.length))return this.treatmentBundle021(event);if(this.isMedicationBatch021(event,list)){if(this.isMedicationBatchChild021(event,list))return"";return this.medicationBatchBundle021(event)}return AH021Base.eventCompact0817.call(this,event)};
AH021.eventRow=function(event){const list=this.eventSource021(event);if(this.treatmentSummaryForChild020?.(event,list))return"";if(this.isMedicationBatchChild021(event,list))return"";return AH021Base.eventRow.call(this,event)};
AH021.homeTimeline013=function(){const source=this.effectiveEvents0817?this.effectiveEvents0817(this.d?.events||[]):this.d?.events||[],visible=this.visibleTimelineEvents021(source),recent=visible.slice(0,10);return`<section class="card homeTimeline013"><div class="cardHead013"><h2>${this.t("timeline")}</h2><button type="button" class="textLink013" data-view="timeline">${this.t("showAll013")}<ha-icon icon="mdi:chevron-right"></ha-icon></button></div><div class="homeTimelineRows013">${recent.map(event=>this.eventCompact0817(event)).join("")||this.empty("noEvents")}</div>${visible.length?`<button type="button" class="moreTimeline013" data-view="timeline">${this.t("showMore013")}<ha-icon icon="mdi:chevron-down"></ha-icon></button>`:""}</section>`};
AH021.eventDetail=function(id){const event=this.eventById?.(id),html=AH021Base.eventDetail.call(this,id);if(!event||event.event_type!=="treatment"||this.treatmentPlanId020?.(event)==null)return html;if(html.includes('data-action="treatment-repeat-021"'))return html;const actions=`<div class="buttons eventActions021"><button type="button" data-action="treatment-copy-021" data-id="${esc(event.id)}"><ha-icon icon="mdi:content-copy"></ha-icon>${this.t("treatmentCopy021")}</button><button type="button" class="primary" data-action="treatment-repeat-021" data-id="${esc(event.id)}"><ha-icon icon="mdi:repeat"></ha-icon>${this.t("treatmentRepeat021")}</button></div>`;return html.replace(/<\/div>\s*$/,`${actions}</div>`)};
AH021.openTreatmentFromHistory021=function(event,copy=false){const planId=this.treatmentPlanId020?.(event),plan=this.treatmentPlanById012?.(planId);if(!plan){this.notify(this.t("treatmentUnavailable021"),true);return}this.openTreatmentPlanExecution012(Number(planId),event.animal_id||this.detail?.animal?.id||"");if(copy&&this.planExecution012){this.planExecution012.notes=String(event.notes||"");this.render()}};
AH021.openMedicationBatchFromHistory021=function(event,mode){const members=this.batchMembers021(event,this.eventSource021(event));if(!members.length)return;const items=members.map(item=>this.eventToMedication0817(item));this.openMedicationBatch0817({animalId:event.animal_id,items,mode})};
AH021.handleClick=async function(event){const button=event.composedPath().find(node=>node?.dataset?.action),action=button?.dataset?.action,id=button?.dataset?.id;if(action==="toggle-treatment-021"){const set=this.expandedTreatmentSet021(),key=String(id||"");set.has(key)?set.delete(key):set.add(key);this.render();return}if(action==="toggle-med-batch-021"){const entry=this.eventById?.(id);if(!entry)return;const key=this.batchId021(entry);if(!key)return;const set=this.expandedMedicationBatchesSet021();set.has(key)?set.delete(key):set.add(key);this.render();return}if(action==="treatment-repeat-021"||action==="treatment-copy-021"){const entry=this.eventById?.(id);if(entry)this.openTreatmentFromHistory021(entry,action==="treatment-copy-021");return}if(action==="batch-repeat-021"||action==="batch-copy-021"){const entry=this.eventById?.(id);if(entry)this.openMedicationBatchFromHistory021(entry,action==="batch-copy-021"?"copy":"repeat");return}return AH021Base.handleClick.call(this,event)};
AH021.render=function(){AH021Base.render.call(this);this.shadowRoot.innerHTML+=`<style>
.bundleGroup021{display:block}.bundleRow021{position:relative;grid-template-columns:auto minmax(0,1fr) auto!important;align-items:center!important}.bundleText021{display:flex!important;min-width:0;flex-direction:column;gap:2px}.bundleText021>b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.bundleText021>span:not(.bundlePreview021){font-size:.82rem;color:var(--secondary-text-color)}.bundlePreview021{display:grid!important;gap:1px;margin-top:2px;color:var(--secondary-text-color)}.bundlePreview021 small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.74rem;line-height:1.2}.bundleChevron021{align-self:center!important;width:34px!important;height:34px!important;min-width:34px!important;padding:0!important;display:grid!important;place-items:center!important;border:0!important;background:transparent!important}.bundleChevron021 ha-icon{width:20px!important;height:20px!important}.bundleChildren021{margin:2px 0 8px 26px;padding:2px 0 2px 12px;border-left:2px solid var(--divider-color);display:grid;gap:2px}.bundleChild021>.row,.bundleActionStep021{margin:0!important}.bundleActionStep021{cursor:default!important}.bundleActions021{display:flex;justify-content:flex-end;flex-wrap:wrap;gap:6px;padding:7px 4px 2px}.eventActions021{margin-top:12px}.medicationBatchSummary021{cursor:pointer}.treatmentSummary021{cursor:pointer}@media(max-width:520px){.bundleChildren021{margin-left:18px;padding-left:8px}.bundlePreview021 small{font-size:.7rem}.bundleActions021{justify-content:stretch}.bundleActions021 button{flex:1;min-width:140px}}
</style>`};
