AH027.taskForm=function(){
 let html=AH027Base.taskForm.call(this),template=document.createElement("template");template.innerHTML=html;const form=template.content.querySelector('form[data-form="task"]');if(!form)return html;
 const kind=form.querySelector('select[name="task_kind"]');if(kind)for(const value of["deworming","supplement","feed"]){if(!kind.querySelector(`option[value="${value}"]`)){const option=document.createElement("option");option.value=value;option.textContent=this.l(value);kind.append(option)}}
 const vaccination=form.querySelector('[data-kind="vaccination"]');if(vaccination){const checks=vaccination.querySelector('.checks');if(checks){const details=document.createElement("details");details.className="vaccineFallback027";const summary=document.createElement("summary");summary.textContent=this.lang()?"Manual targets / fallback":"Zielkrankheiten manuell / Fallback";details.append(summary,checks);vaccination.insertBefore(details,vaccination.firstChild)}const vaccineInput=vaccination.querySelector('input[name="planned_vaccine_name"]');if(vaccineInput)vaccineInput.setAttribute("list","gabe-task-vaccines-027")}
 const units=(this.c?.dose_units||["mg","g","ml","dose"]).map(unit=>`<option value="${esc(unit)}">${esc(this.l(unit))}</option>`).join(""),routes=(this.c?.administration_routes||[]).map(route=>`<option value="${esc(route)}">${esc(this.l(route))}</option>`).join("");
 const fields=(type,extra="")=>`<fieldset class="wide gabeTaskFields027" data-kind="${type}" hidden><label><span>${this.t("taskProduct027")}</span><input name="${type==="deworming"?"planned_medication_name":"planned_product_name"}" list="gabe-task-${type}-027" required></label><label><span>${this.t("dose")}</span><input type="number" name="planned_dose" min="0.000001" step="any" required></label><label><span>${this.t("dose_unit")}</span><select name="planned_dose_unit" required>${units}</select></label>${type!=="feed"?`<label><span>${this.t("route")}</span><select name="planned_route"><option value="">–</option>${routes}</select></label>`:""}${extra}</fieldset>`;
 const doseBasis=`<label><span>${this.t("doseBasis027")}</span><select name="dose_basis"><option value="per_animal">${this.t("dosePerAnimal027")}</option><option value="per_kg">${this.t("dosePerKg027")}</option><option value="per_l_water">${this.t("dosePerWater027")}</option><option value="per_kg_feed">${this.t("dosePerFeed027")}</option></select></label>`;
 const feedStatus=`<label><span>${this.t("feedStatus027")}</span><select name="feed_status"><option value="offered">${this.t("feedOffered027")}</option><option value="consumed">${this.t("feedConsumed027")}</option></select></label>`;
 form.querySelector('[data-kind="veterinary_visit"]')?.insertAdjacentHTML("afterend",`${fields("deworming")}${fields("supplement",doseBasis)}${fields("feed",feedStatus)}`);
 form.insertAdjacentHTML("beforeend",`<datalist id="gabe-task-vaccines-027">${this.gabeOptions027("vaccination")}</datalist><datalist id="gabe-task-deworming-027">${this.gabeOptions027("deworming")}</datalist><datalist id="gabe-task-supplement-027">${this.gabeOptions027("supplement")}</datalist><datalist id="gabe-task-feed-027">${this.gabeOptions027("feed")}</datalist>`);
 return template.innerHTML
};
AH027.syncTask=function(form){AH027Base.syncTask.call(this,form);if(!form)return;const kind=form.elements.task_kind?.value;for(const fieldset of form.querySelectorAll('.gabeTaskFields027')){fieldset.hidden=fieldset.dataset.kind!==kind;for(const field of fieldset.querySelectorAll('input,select,textarea'))field.disabled=fieldset.hidden}}

AH027.gabeTaskExecutionForm027=function(item){const planned=item?.planned||item?.task_recording_template||{},kind=item?.task_kind||"supplement",gabeType=kind==="deworming"?"deworming":kind==="feed"?"feed":"supplement",name=planned.product_name||planned.medication_name||item?.task_title||"",dose=planned.dose||"",unit=planned.dose_unit||"dose",route=planned.route||"",now=this.nowTemporal023?this.nowTemporal023(true):{date:this.d?.today||"",time:""},units=this.c?.dose_units||["mg","g","ml","dose"],routes=this.c?.administration_routes||[];return`<h2><ha-icon icon="${this.gabeKindIcon027(gabeType)}"></ha-icon>${esc(item?.task_title||this.gabeKindLabel027(gabeType))}</h2><form data-form="execute-gabe-027"><input type="hidden" name="occurrence_id" value="${esc(item?.id||"")}"><input type="hidden" name="gabe_type" value="${gabeType}"><label class="wide"><span>${this.t("taskProduct027")}</span><input name="product_name" value="${esc(name)}" list="gabe-exec-products-027" required></label><label><span>${this.t("dose")}</span><input name="dose" type="number" min="0.000001" step="any" value="${esc(dose)}" required></label><label><span>${this.t("dose_unit")}</span><select name="dose_unit">${units.map(value=>`<option value="${esc(value)}" ${String(value)===String(unit)?"selected":""}>${esc(this.l(value))}</option>`).join("")}</select></label>${gabeType!=="feed"?`<label><span>${this.t("route")}</span><select name="route"><option value="">–</option>${routes.map(value=>`<option value="${esc(value)}" ${String(value)===String(route)?"selected":""}>${esc(this.l(value))}</option>`).join("")}</select></label>`:""}<label><span>${this.t("start_date")}</span><input type="date" name="occurred_date" value="${esc(now.date)}" required></label><label><span>${this.t("time0817")}</span><input type="time" name="occurred_time" value="${esc(now.time||"")}"></label>${gabeType==="supplement"?`<label><span>${this.t("doseBasis027")}</span><select name="dose_basis"><option value="per_animal">${this.t("dosePerAnimal027")}</option><option value="per_kg">${this.t("dosePerKg027")}</option><option value="per_l_water">${this.t("dosePerWater027")}</option><option value="per_kg_feed">${this.t("dosePerFeed027")}</option></select></label>`:""}${gabeType==="feed"?`<label><span>${this.t("feedStatus027")}</span><select name="feed_status"><option value="offered">${this.t("feedOffered027")}</option><option value="consumed">${this.t("feedConsumed027")}</option></select></label>`:""}${this.area("notes","notes")}<datalist id="gabe-exec-products-027">${this.gabeOptions027(gabeType)}</datalist>${this.buttons()}</form>`};
AH027.execForm=function(item){return["deworming","supplement","feed"].includes(String(item?.task_kind||""))?this.gabeTaskExecutionForm027(item):AH027Base.execForm.call(this,item)};

AH027.medicationBatchForm0817=function(){let html=AH027Base.medicationBatchForm0817.call(this),state=this.medBatch0817||{},kind=this.gabeType027||"medication",locked=state.mode==="edit"||state.mode==="correction";if(locked)kind="medication";this.gabeType027=kind;const selector=`<label class="wide gabeTypeField027"><span>${this.t("gabeType027")}</span><select data-gabe-type027 ${locked?"disabled":""}>${this.gabeKinds027().map(value=>`<option value="${value}" ${value===kind?"selected":""}>${this.gabeKindLabel027(value)}</option>`).join("")}</select></label>`,extra=kind==="supplement"?`<label class="gabeExtra027"><span>${this.t("doseBasis027")}</span><select name="dose_basis_027"><option value="per_animal">${this.t("dosePerAnimal027")}</option><option value="per_kg">${this.t("dosePerKg027")}</option><option value="per_l_water">${this.t("dosePerWater027")}</option><option value="per_kg_feed">${this.t("dosePerFeed027")}</option></select></label>`:kind==="feed"?`<label class="gabeExtra027"><span>${this.t("feedStatus027")}</span><select name="feed_status_027"><option value="offered">${this.t("feedOffered027")}</option><option value="consumed">${this.t("feedConsumed027")}</option></select></label>`:"",list=`<datalist id="gabe-products-027">${this.gabeOptions027(kind)}</datalist>`;html=html.replace(/(<form[^>]*data-form="medication-batch-0817"[^>]*>)/,`$1${selector}${extra}`);return html.replace("</form>",`${list}</form>`)};
AH027.decorateGabeCapture027=function(){const form=this.shadowRoot.querySelector('form[data-form="medication-batch-0817"]');if(!form)return;for(const input of form.querySelectorAll('input[name^="product_name_"]'))input.setAttribute("list","gabe-products-027")};

AH027.planComponentRow012=function(item,index,units,routes){let html=AH027Base.planComponentRow012.call(this,item,index,units,routes);if(!item.optional)return html;const control=`<label class="planDefaultSelected027"><input type="checkbox" data-plan-default-selected027 data-index="${index}" ${item.default_selected?"checked":""}><span>${this.t("defaultSelected027")}</span></label>`;return html.replace("</article>",`${control}</article>`)};
AH027.openTreatmentPlanExecution012=function(planId,animalId=""){AH027Base.openTreatmentPlanExecution012.call(this,planId,animalId);const plan=this.treatmentPlanById012?.(planId);if(this.planExecution012&&plan){this.planExecution012.selectedOptional=(plan.components||[]).map((item,index)=>item.optional&&item.default_selected?index:null).filter(index=>index!==null);this.render()}};
