 tasks(){const q=this.filter.toLowerCase(),a=this.d.occurrences.filter(x=>!q||[x.task_title,x.animal_name,x.task_kind,x.status].some(y=>String(y||"").toLowerCase().includes(q)));return`${this.heading("tasks",`<button class="primary" data-action="create-task"><ha-icon icon="mdi:clipboard-plus"></ha-icon>${this.t("createTask")}</button>`)}${this.group("overdue",a.filter(x=>x.is_overdue))}${this.group("dueToday",a.filter(x=>x.is_today))}${this.group("upcoming",a.filter(x=>x.is_upcoming).slice(0,100))}${this.group("completed",a.filter(x=>x.status!=="pending").slice(0,100))}<section class="card"><h2>${this.t("tasks")}</h2>${this.d.tasks.map(x=>`<div class="row"><ha-icon icon="${I[x.task_kind]||I.reminder}"></ha-icon><div><b>${esc(x.title)}</b><span>${esc(x.animal_name||this.t("general"))} · ${this.l(x.task_kind)}</span></div><button data-action="toggle" data-id="${x.id}">${this.t(x.is_active?"deactivate":"activate")}</button></div>`).join("")||this.empty("noTasks")}</section>`}
 group(k,a){return`<section class="card"><h2>${this.t(k)} <small>${a.length}</small></h2>${this.rows(a)}</section>`}rows(a){return a.map(x=>this.occRow(x)).join("")||this.empty("noTasks")}
 occRow(x){return`<div class="row ${x.is_overdue?"over":""}"><ha-icon icon="${I[x.task_kind]||I.reminder}"></ha-icon><div><b>${esc(x.task_title)}</b><span>${esc(x.animal_name||this.t("general"))} · ${this.fmt(x.scheduled_local,true)} · ${this.l(x.status)}</span></div>${x.status==="pending"?`<div class="rowBtns"><button class="primary" data-action="execute" data-id="${x.id}">${this.t("execute")}</button><button data-action="resolve" data-resolution="skip" data-id="${x.id}">${this.t("skip")}</button><button data-action="resolve" data-resolution="cancel" data-id="${x.id}">${this.t("cancel")}</button></div>`:""}</div>`}
 calendar(){const m=new Map;for(const x of this.d.occurrences.filter(y=>y.status==="pending")){const k=x.scheduled_date;(m.get(k)||m.set(k,[]).get(k)).push(x)}return`${this.heading("calendar")}<section class="days">${[...m].sort().map(([d,a])=>`<article class="day"><time>${this.fmt(d)}</time><div>${a.map(x=>this.occRow(x)).join("")}</div></article>`).join("")||this.empty("noTasks")}</section>`}
 timeline(){const q=this.filter.toLowerCase(),a=this.d.events.filter(x=>!q||[x.animal_name,x.title,x.event_type,x.notes,x.id].some(y=>String(y||"").toLowerCase().includes(q)));return`${this.heading("timeline",`<button data-action="record-event"><ha-icon icon="mdi:note-plus"></ha-icon>${this.t("recordEvent")}</button>`)}<section class="card">${a.map(x=>this.eventRow(x)).join("")||this.empty("noEvents")}</section>`}
 eventRow(e){const ex=e.data?.task_execution,v=e.value!=null?`${this.num(e.value)} ${esc(e.unit)}`:"";return`<div class="row event"><ha-icon icon="${I[e.event_type]||I.other}"></ha-icon><div><b>${esc(e.title)}</b><span>${esc(e.animal_name||"")} · ${this.l(e.event_type)} · ${this.fmt(e.occurred_at,true)}</span>${e.notes?`<small>${esc(e.notes)}</small>`:""}${ex?this.execution(ex):e.correction_of_event_id?`<small>Korrektur: ${esc(e.correction_of_event_id)}</small>`:""}</div>${v?`<strong>${v}</strong>`:""}</div>`}
 obj(o){const z=Object.entries(o||{}).filter(([k,v])=>k!=="catalog"&&v!=null&&v!==""&&(!Array.isArray(v)||v.length));return z.length?`<dl>${z.map(([k,v])=>`<div><dt>${esc(this.l(k))}</dt><dd>${esc(Array.isArray(v)?v.map(x=>this.l(x)).join(", "):typeof v==="object"?JSON.stringify(v):this.l(v))}</dd></div>`).join("")}</dl>`:"–"}
 execution(x){return`<details><summary>${this.t("plannedActual")}</summary><p><b>${this.t("timing")}:</b> ${this.l(x.timing_status)} · <b>${this.t("deviation")}:</b> ${this.num(x.timing_deviation_minutes||0,0)} ${this.t("minutes")}${x.deviation_reason?` · ${esc(x.deviation_reason)}`:""}</p><div class="exec"><section><h4>${this.t("planned")}</h4>${this.obj(x.planned)}</section><section><h4>${this.t("actual")}</h4>${this.obj(x.actual)}</section></div></details>`}
 animalDetail(){if(!this.detail)return this.empty("loading");const a=this.detail.animal,w=a.latest_weight,p=this.detail.occurrences.filter(x=>x.status==="pending");return`${this.heading("animals",`<button data-view="animals"><ha-icon icon="mdi:arrow-left"></ha-icon></button>`)}<section class="hero"><ha-icon icon="mdi:paw"></ha-icon><div><h1>${esc(a.name)}</h1><p>${esc(a.species)}${a.breed?` · ${esc(a.breed)}`:""} · ${this.l(a.status)}</p></div><div class="actions"><button data-action="edit-animal" data-id="${a.id}">${this.t("edit")}</button><button data-action="animal-status" data-id="${a.id}">${this.t("changeStatus")}</button><button data-action="${a.is_archived?"restore":"archive"}" data-id="${a.id}">${this.t(a.is_archived?"restore":"archive")}</button></div></section>${this.quick(a.id)}<section class="stats">${this.stat("mdi:scale",w?`${this.num(w.original_value)} ${w.original_unit}`:"–","currentWeight")}${this.stat("mdi:clipboard",p.length,"openTasks")}${this.stat("mdi:calendar",a.birth_date?this.fmt(a.birth_date):"–","birth_date")}${this.stat("mdi:identifier",a.id,"technicalId")}</section><section class="cols"><article class="card"><h2>${this.t("masterData")}</h2>${this.obj({species:a.species,breed:a.breed,color:a.color,sex:a.sex,birth_date:a.birth_date,arrival_date:a.arrival_date,status:a.status})}</article><article class="card"><h2>${this.t("upcoming")}</h2>${this.rows(p.slice(0,20))}</article></section><section class="card"><h2>${this.t("plannedActual")}</h2>${this.detail.events.map(x=>this.eventRow(x)).join("")||this.empty("noEvents")}</section>`}
 empty(k){return`<div class="empty">${this.t(k)}</div>`}
 modalHtml(){if(!this.modal)return"";return`<div class="back"><section class="modal"><button class="x" data-action="close"><ha-icon icon="mdi:close"></ha-icon></button>${this.form()}</section></div>`}
