Object.assign(T,{
 offLabelPolicy012:["Off-Label-Anzeige","Off-label display"],
 offLabelShowAll012:["Alle Medikamente immer anzeigen","Always show all medications"],
 offLabelShowAllHint012:["Tierart-Zuordnungen beeinflussen die Auswahl nicht und werden nicht markiert.","Species assignments do not restrict or mark the selection."],
 offLabelMarked012:["Alle anzeigen und Off-Label markieren","Show all and mark off-label"],
 offLabelMarkedHint012:["Präparate anderer Tierarten bleiben sichtbar und werden mit ⚠ Off-Label gekennzeichnet.","Products for other species remain visible and are marked ⚠ Off-label."],
 offLabelHide012:["Off-Label grundsätzlich ausblenden","Always hide off-label"],
 offLabelHideHint012:["Bei einem Tier werden nur passende oder tierartunabhängige Präparate angeboten.","Only matching or species-independent products are offered for an animal."],
 offLabelDemand012:["Off-Label nur auf ausdrücklichen Wunsch anzeigen","Show off-label only on request"],
 offLabelDemandHint012:["Standardmässig ausgeblendet. Nur in diesem Modus erscheint bei der Erfassung die Option «Off-Label anzeigen».","Hidden by default. Only in this mode does capture show the option to reveal off-label products."],
 offLabelReveal012:["Off-Label anzeigen","Show off-label"],
 offLabelSaved012:["Off-Label-Einstellung gespeichert","Off-label setting saved"],
 planComponents012:["Bestandteile / Schritte","Components / steps"],
 addPlanComponent012:["Bestandteil hinzufügen","Add component"],
 componentType012:["Art","Type"],
 componentMedication012:["Medikament","Medication"],
 componentSupplement012:["Nahrungsergänzung","Supplement"],
 componentFeed012:["Futter","Feed"],
 componentAction012:["Handlung / Pflegeschritt","Action / care step"],
 componentName012:["Produkt / Handlung","Product / action"],
 componentAmount012:["Menge / Dosis","Amount / dose"],
 componentInstructions012:["Hinweis / Durchführung","Instruction / procedure"],
 executeTreatmentPlan012:["Behandlungsplan ausführen","Execute treatment plan"],
 chooseTreatmentPlan012:["Behandlungsplan auswählen","Choose treatment plan"],
 treatmentPlanExecuteHint012:["Alle hinterlegten Bestandteile werden gemeinsam dokumentiert. Medikamente und Supplemente erhalten zusätzlich eigene Medikamenteneinträge.","All stored components are documented together. Medications and supplements additionally receive their own medication records."],
 treatmentPlanExecuted012:["Behandlungsplan dokumentiert","Treatment plan recorded"],
 noPlanComponents012:["Mindestens ein Bestandteil oder Handlungsschritt ist erforderlich.","At least one component or action step is required."],
 treatmentPlanLinked012:["Behandlungsplan ist mit der Aufgabe verknüpft.","Treatment plan is linked to the task."]
});
Object.assign(L,{pinch:["Messerspitze","Pinch"],feed:["Futter","Feed"],action:["Handlung","Action"],supplement:["Nahrungsergänzung","Supplement"]});
const AH012=AnimalHealthPanel.prototype;
const AH012Base={
 load:AH012.load,
 medicationOptions0817:AH012.medicationOptions0817,
 medicationBatchForm0817:AH012.medicationBatchForm0817,
 medicationSettings0817:AH012.medicationSettings0817,
 treatmentSettings011:AH012.treatmentSettings011,
 taskForm:AH012.taskForm,
 comboCandidates083:AH012.comboCandidates083,
 applyTreatmentPlan011:AH012.applyTreatmentPlan011,
 saveTask:AH012.saveTask,
 form:AH012.form,
 handleChange:AH012.handleChange,
 handleInput:AH012.handleInput,
 handleClick:AH012.handleClick,
 handleSubmit:AH012.handleSubmit,
 render:AH012.render
};
AH012.loadV0912=async function(){try{this.v0912=await this.ws(`${D}/v0912/state`);this.v0911=this.v0911||{};this.v0911.treatment_plans=this.v0912?.treatment_plans||[]}catch(_error){this.v0912={off_label_mode:"show_all",treatment_plans:this.v0911?.treatment_plans||[],status_changes:[]}}};
AH012.load=async function(){await AH012Base.load.call(this);if(!this.h||!this.d)return;await this.loadV0912();this.render()};
AH012.offLabelMode012=function(){const value=String(this.v0912?.off_label_mode||"");if(["show_all","show_marked","hide","on_demand"].includes(value))return value;return this.v0817?.off_label_enabled?"show_marked":"show_all"};
AH012.medicationSpeciesList012=function(form){if(!form)return[];const direct=form.elements?.animal_id?.value;if(direct){const animal=this.animal(direct);return animal?[this.speciesId(animal.species)]:[]}const ids=[...form.querySelectorAll?.('[name="device_ids"]:checked')||[]].map(input=>input.value),species=[...new Set((this.d?.animals||[]).filter(animal=>ids.includes(animal.device_id)).map(animal=>this.speciesId(animal.species)).filter(Boolean))];if(!species.length&&this.modal?.animalId){const animal=this.animal(this.modal.animalId);if(animal)species.push(this.speciesId(animal.species))}return species};
AH012.candidateOffLabel012=function(candidate,speciesList){const targets=(candidate.species_ids||[]).filter(Boolean);if(!speciesList.length||!targets.length)return false;return speciesList.some(species=>!targets.includes(species))};
AH012.allowOffLabel012=function(offLabel,requested=false){const mode=this.offLabelMode012();if(mode==="show_all"||mode==="show_marked")return true;if(!offLabel)return true;return mode==="on_demand"&&Boolean(requested)};
AH012.markOffLabel012=function(offLabel,requested=false){if(!offLabel)return false;const mode=this.offLabelMode012();return mode==="show_marked"||(mode==="on_demand"&&Boolean(requested))};
AH012.medicationOptionsForSpecies012=function(speciesList,current="",requested=false){const standard=(this.v083?.medicines||[]).map(item=>({value:item.name,custom:false,unknown:false,source:"catalog",species_ids:(item.target_species||[]).map(String)})),custom=(this.v0817?.medications||[]).map(item=>({value:item.name,custom:true,unknown:false,source:"medication",species_ids:item.species_id?[String(item.species_id)]:[]})),remembered=(this.v083?.custom_values||[]).filter(item=>item.kind==="medication").map(item=>({value:item.value,custom:true,unknown:true,source:"manual",species_ids:item.species_id?[String(item.species_id)]:[]})),result=[],seen=new Set;for(const source of[...custom,...standard,...remembered]){const value=String(source.value||"").trim(),key=this.normPlan011?this.normPlan011(value):value.toLocaleLowerCase();if(!value||seen.has(key))continue;const off=this.candidateOffLabel012(source,speciesList);if(!this.allowOffLabel012(off,requested))continue;seen.add(key);result.push({...source,value,offlabel:this.markOffLabel012(off,requested)})}if(current){const key=this.normPlan011?this.normPlan011(current):String(current).toLocaleLowerCase();if(!seen.has(key))result.unshift({value:current,custom:true,manual:true,source:"manual",species_ids:[],offlabel:false})}return result.sort((a,b)=>a.value.localeCompare(b.value,undefined,{sensitivity:"base"}))};
AH012.medicationOptions0817=function(animalId,current="",requested=null){const animal=this.animal(animalId),species=animal?[this.speciesId(animal.species)]:[],show=requested==null?Boolean(this.medBatch0817?.showOffLabel):Boolean(requested);return this.medicationOptionsForSpecies012(species,current,show)};
AH012.comboCandidates083=function(kind,form){if(kind!=="medication")return AH012Base.comboCandidates083.call(this,kind,form);const species=this.medicationSpeciesList012(form),requested=Boolean(form?.querySelector?.('[name="show_off_label"]:checked')),current=form?.querySelector?.('[data-combo083="medication"]')?.value||"";return this.medicationOptionsForSpecies012(species,current,requested)};
AH012.planOffLabel012=function(plan,speciesList){return Boolean(plan?.species_id&&speciesList.length&&speciesList.some(species=>String(plan.species_id)!==String(species)))};
AH012.treatmentPlansForSpecies012=function(target,speciesList=[],requested=false){const plans=(this.v0912?.treatment_plans||this.v0911?.treatment_plans||[]).filter(plan=>plan.list_as===target||plan.list_as==="both"),result=[];for(const plan of plans){const off=this.planOffLabel012(plan,speciesList);if(!this.allowOffLabel012(off,requested))continue;result.push({...plan,_offlabel012:this.markOffLabel012(off,requested)})}return result.sort((a,b)=>String(a.name).localeCompare(String(b.name),undefined,{sensitivity:"base"}))};
AH012.medicationOptionLabel011=function(option){const parts=[option.value];if(option.offlabel)parts.push(`⚠ ${this.t("offLabel011")}`);return parts.join(" · ")};
AH012.medicationBatchForm0817=function(){let html=AH012Base.medicationBatchForm0817.call(this),animalId=this.medBatch0817?.animalId||this.detail?.animal?.id||"",animal=this.animal(animalId),species=animal?[this.speciesId(animal.species)]:[],requested=Boolean(this.medBatch0817?.showOffLabel),plans=this.treatmentPlansForSpecies012("medication",species,requested),mode=this.offLabelMode012(),controls=[];if(plans.length)controls.push(`<label class="planChooser012"><span>${this.t("executeTreatmentPlan012")}</span><select data-treatment-plan-run012><option value="">${this.t("chooseTreatmentPlan012")}</option>${plans.map(plan=>`<option value="${esc(plan.id)}">${esc(plan.name)}${plan._offlabel012?` · ⚠ ${this.t("offLabel011")}`:""}</option>`).join("")}</select></label>`);if(mode==="on_demand")controls.push(`<label class="offLabelReveal012"><input type="checkbox" data-off-label-med012 ${requested?"checked":""}><span>${this.t("offLabelReveal012")}</span></label>`);if(controls.length)html=html.replace('<div class="wide medItems0817">',`<fieldset class="wide medicationExtras012"><legend>${this.t("moreDetails")}</legend>${controls.join("")}</fieldset><div class="wide medItems0817">`);return html};
AH012.medicationSettings0817=function(){const units=this.c?.dose_units||["mcg","mg","g","ul","ml","drop","tablet","dose","mark","pinch"],routes=this.c?.administration_routes||[],species=this.c?.species||[],meds=this.v0817?.medications||[],mode=this.offLabelMode012(),speciesOptions=species.map(item=>{const id=String(item.id||item.value||""),label=(this.lang()?item.name_en:item.name_de)||item.name||id;return`<option value="${esc(id)}">${esc(label)}</option>`}).join(""),choice=(value,label,hint)=>`<label class="offPolicyChoice012"><input type="radio" name="mode" value="${value}" ${mode===value?"checked":""}><span><b>${this.t(label)}</b><small>${this.t(hint)}</small></span></label>`;return`<section class="card settings0817 medicationSettings012"><h2>${this.t("medicationManagement0817")}</h2><form data-form="v0912-offlabel" class="offLabelPolicy012"><fieldset><legend>${this.t("offLabelPolicy012")}</legend>${choice("show_all","offLabelShowAll012","offLabelShowAllHint012")}${choice("show_marked","offLabelMarked012","offLabelMarkedHint012")}${choice("hide","offLabelHide012","offLabelHideHint012")}${choice("on_demand","offLabelDemand012","offLabelDemandHint012")}</fieldset><button type="submit">${this.t("save")}</button></form><form data-form="v0817-medication" class="medAdminForm0817"><label><span>${this.t("medication")}</span><input name="name" required></label><label><span>${this.t("species")}</span><select name="species_id"><option value="">${this.t("allSpecies0817")}</option>${speciesOptions}</select></label><label><span>${this.t("defaultDoseUnit0817")}</span><select name="default_unit">${units.map(unit=>`<option value="${esc(unit)}">${esc(this.l(unit))}</option>`).join("")}</select></label><label><span>${this.t("defaultRoute0817")}</span><select name="default_route"><option value="">–</option>${routes.map(route=>`<option value="${esc(route)}">${esc(this.l(route))}</option>`).join("")}</select></label><button type="submit" class="primary"><ha-icon icon="mdi:plus-circle-outline"></ha-icon>${this.t("addMedication0817")}</button></form>${meds.length?`<div class="managedMeds0817">${meds.map(item=>`<span><b>${esc(item.name)}</b><small>${item.species_id?esc(item.species_id)+" · ":""}${esc(this.l(item.default_unit))}${item.default_route?` · ${esc(this.l(item.default_route))}`:""}</small></span>`).join("")}</div>`:""}</section>`};
AH012.blankPlanComponent012=function(type="medication"){return{type,name:"",dose:"",unit:type==="action"?"":"dose",route:"",instructions:""}};
AH012.ensurePlanDraft012=function(){if(!this.planDraft012)this.planDraft012={name:"",species_id:"",list_as:"task",description:"",components:[this.blankPlanComponent012()]};if(!Array.isArray(this.planDraft012.components)||!this.planDraft012.components.length)this.planDraft012.components=[this.blankPlanComponent012()];return this.planDraft012};
AH012.planComponentRow012=function(item,index,units,routes){const action=item.type==="action";return`<article class="planComponent012"><div class="planComponentHead012"><label><span>${this.t("componentType012")}</span><select data-plan-component012="type" data-index="${index}">${[["medication","componentMedication012"],["supplement","componentSupplement012"],["feed","componentFeed012"],["action","componentAction012"]].map(([value,label])=>`<option value="${value}" ${item.type===value?"selected":""}>${this.t(label)}</option>`).join("")}</select></label><label class="planComponentName012"><span>${this.t("componentName012")}</span><input data-plan-component012="name" data-index="${index}" value="${esc(item.name||"")}" required></label><button type="button" data-action="plan-component-remove-012" data-index="${index}" title="${this.t("delete")}"><ha-icon icon="mdi:delete-outline"></ha-icon></button></div>${action?"":`<div class="planDose012"><label><span>${this.t("componentAmount012")}</span><input type="number" min="0.000001" step="any" data-plan-component012="dose" data-index="${index}" value="${esc(item.dose||"")}" required></label><label><span>${this.t("dose_unit")}</span><select data-plan-component012="unit" data-index="${index}">${units.map(unit=>`<option value="${esc(unit)}" ${item.unit===unit?"selected":""}>${esc(this.l(unit))}</option>`).join("")}</select></label><label><span>${this.t("route")}</span><select data-plan-component012="route" data-index="${index}"><option value="">–</option>${routes.map(route=>`<option value="${esc(route)}" ${item.route===route?"selected":""}>${esc(this.l(route))}</option>`).join("")}</select></label></div>`}<label class="planInstruction012"><span>${this.t("componentInstructions012")}</span><input data-plan-component012="instructions" data-index="${index}" value="${esc(item.instructions||"")}"></label></article>`};
AH012.treatmentSettings011=function(){const draft=this.ensurePlanDraft012(),plans=this.v0912?.treatment_plans||[],species=this.c?.species||[],units=this.c?.dose_units||["mcg","mg","g","ul","ml","drop","tablet","dose","mark","pinch"],routes=this.c?.administration_routes||[],speciesOptions=species.map(item=>{const id=String(item.id||item.value||""),label=(this.lang()?item.name_en:item.name_de)||item.name||id;return`<option value="${esc(id)}" ${draft.species_id===id?"selected":""}>${esc(label)}</option>`}).join(""),targetLabel=value=>this.t(value==="medication"?"listAsMedication011":value==="both"?"listAsBoth011":"listAsTask011"),componentSummary=plan=>(plan.components||[]).map(item=>item.type==="action"?item.name:`${item.name} · ${this.num(item.dose)} ${this.l(item.unit)}`).join("; ");return`<section class="card treatmentSettings011 treatmentSettings012"><h2>${this.t("treatmentPlans011")}</h2><p>${this.t("treatmentPlansHint011")}</p><form data-form="v0912-treatment" class="treatmentAdminForm012"><div class="planTop012"><label><span>${this.t("name")}</span><input data-plan-top012="name" value="${esc(draft.name||"")}" required></label><label><span>${this.t("species")}</span><select data-plan-top012="species_id"><option value="">${this.t("allSpecies0817")}</option>${speciesOptions}</select></label><label><span>${this.t("listAs011")}</span><select data-plan-top012="list_as"><option value="task" ${draft.list_as==="task"?"selected":""}>${this.t("listAsTask011")}</option><option value="medication" ${draft.list_as==="medication"?"selected":""}>${this.t("listAsMedication011")}</option><option value="both" ${draft.list_as==="both"?"selected":""}>${this.t("listAsBoth011")}</option></select></label></div><label class="planDescription012"><span>${this.t("treatmentDescription011")}</span><textarea rows="2" data-plan-top012="description">${esc(draft.description||"")}</textarea></label><fieldset class="planComponents012"><legend>${this.t("planComponents012")}</legend>${draft.components.map((item,index)=>this.planComponentRow012(item,index,units,routes)).join("")}<button type="button" data-action="plan-component-add-012"><ha-icon icon="mdi:plus-circle-outline"></ha-icon>${this.t("addPlanComponent012")}</button></fieldset><button type="submit" class="primary"><ha-icon icon="mdi:content-save-outline"></ha-icon>${this.t("addTreatmentPlan011")}</button></form>${plans.length?`<div class="managedTreatments011 managedTreatments012">${plans.map(plan=>`<div><span><b>${esc(plan.name)}</b><small>${[plan.species_id||this.t("allSpecies0817"),targetLabel(plan.list_as)].map(esc).join(" · ")}</small>${plan.description?`<em>${esc(plan.description)}</em>`:""}<small>${esc(componentSummary(plan))}</small></span><button type="button" data-action="delete-treatment-012" data-id="${esc(plan.id)}" title="${esc(this.t("delete"))}"><ha-icon icon="mdi:delete-outline"></ha-icon></button></div>`).join("")}</div>`:""}</section>`};
AH012.updatePlanDraft012=function(input){const draft=this.ensurePlanDraft012();if(input?.dataset?.planTop012){draft[input.dataset.planTop012]=input.value;return true}if(input?.dataset?.planComponent012!==undefined){const index=Number(input.dataset.index),item=draft.components[index];if(!item)return false;item[input.dataset.planComponent012]=input.value;if(input.dataset.planComponent012==="type"&&input.value==="action"){item.dose="";item.unit="";item.route=""}else if(input.dataset.planComponent012==="type"&&!item.unit)item.unit="dose";return true}return false};
AH012.treatmentPlanById012=function(id){return(this.v0912?.treatment_plans||[]).find(plan=>String(plan.id)===String(id))||null};
AH012.openTreatmentPlanExecution012=function(planId,animalId=""){const plan=this.treatmentPlanById012(planId);if(!plan)return;const now=this.nowFields0817?this.nowFields0817():{date:this.d?.today||"",time:""};this.planExecution012={planId:Number(plan.id),animalId:animalId||this.detail?.animal?.id||"",date:now.date,time:now.time,notes:""};this.modal={type:"treatment-plan-execute-012"};this.render()};
AH012.treatmentPlanExecutionForm012=function(){const state=this.planExecution012||{},plan=this.treatmentPlanById012(state.planId),animals=(this.d?.animals||[]).filter(animal=>!animal.is_archived);if(!plan)return`<h2>${this.t("treatmentPlan011")}</h2>${this.empty("noEvents")}`;const icon={medication:"mdi:pill",supplement:"mdi:bottle-tonic-plus-outline",feed:"mdi:food-apple-outline",action:"mdi:hand-heart"};return`<h2><ha-icon icon="mdi:clipboard-pulse-outline"></ha-icon>${esc(plan.name)}</h2><form data-form="treatment-plan-execute-012"><p class="wide treatmentExecHint012">${this.t("treatmentPlanExecuteHint012")}</p>${plan.description?`<p class="wide treatmentExecDescription012">${esc(plan.description)}</p>`:""}<label><span>${this.t("animal")}</span><select name="animal_id" required>${animals.map(animal=>`<option value="${esc(animal.id)}" ${String(animal.id)===String(state.animalId)?"selected":""}>${esc(animal.name)}</option>`).join("")}</select></label><label><span>${this.t("administeredAt0817")}</span><input type="date" name="date" value="${esc(state.date||this.d?.today||"")}" required></label><label><span>${this.t("time0817")}</span><input type="time" name="time" value="${esc(state.time||"")}" required></label><section class="wide treatmentExecComponents012">${(plan.components||[]).map(item=>`<div><ha-icon icon="${icon[item.type]||"mdi:circle-small"}"></ha-icon><span><b>${esc(item.name)}</b><small>${item.type==="action"?this.t("componentAction012"):[`${this.num(item.dose)} ${this.l(item.unit)}`,item.route?this.l(item.route):"",item.instructions||""].filter(Boolean).map(String).join(" · ")}</small></span></div>`).join("")}</section><label class="wide"><span>${this.t("notes")}</span><textarea name="notes" rows="2">${esc(state.notes||"")}</textarea></label><div class="buttons wide"><button type="button" data-action="close">${this.t("close")}</button><button type="submit" class="primary"><ha-icon icon="mdi:check-all"></ha-icon>${this.t("executeTreatmentPlan012")}</button></div></form>`};
AH012.taskForm=function(){let html=AH012Base.taskForm.call(this),mode=this.offLabelMode012(),toggle=`<label class="wide offLabelToggle083 offLabelToggle012"><input type="checkbox" name="show_off_label"><span>${this.t("offLabelReveal012")}</span></label>`,planField=`<fieldset class="wide treatmentTask011 treatmentTask012" data-kind="treatment" hidden><label><span>${this.t("treatmentPlan011")}</span><input name="treatment_plan_name" data-treatment-plan011 list="treatment-task-options-012" placeholder="${esc(this.t("treatmentSelect011"))}" autocomplete="off"><datalist id="treatment-task-options-012"></datalist></label><input type="hidden" name="planned_treatment_plan_id" value=""></fieldset>`;html=html.replace(/<label class="wide offLabelToggle083[^>]*>[\s\S]*?<\/label>/g,"");if(mode==="on_demand")html=html.replace(/(<fieldset class="wide" data-kind="medication"[^>]*>[\s\S]*?)(<\/fieldset>)/,(_all,start,end)=>start+toggle+end);if(/<fieldset class="wide treatmentTask011[\s\S]*?<\/fieldset>/.test(html))html=html.replace(/<fieldset class="wide treatmentTask011[\s\S]*?<\/fieldset>/,planField);else html=html.replace('<fieldset class="wide" data-kind="health_check"',`${planField}<fieldset class="wide" data-kind="health_check"`);return html};
AH012.refreshTaskOptions012=function(form){if(!form)return;const species=this.medicationSpeciesList012(form),requested=Boolean(form.querySelector('[name="show_off_label"]:checked'),),meds=this.medicationOptionsForSpecies012(species,form.elements.planned_medication_name?.value||"",requested),medList=form.querySelector('#all-medications-011');if(medList)medList.innerHTML=meds.map(option=>`<option value="${esc(option.value)}">${esc(this.medicationOptionLabel011(option))}</option>`).join("");const plans=this.treatmentPlansForSpecies012("task",species,requested),planList=form.querySelector('#treatment-task-options-012');if(planList)planList.innerHTML=plans.map(plan=>`<option value="${esc(plan.name)}">${esc([plan.description,plan._offlabel012?`⚠ ${this.t("offLabel011")}`:""].filter(Boolean).join(" · ")||plan.name)}</option>`).join("")};
AH012.applyTreatmentPlan011=function(input){const form=input?.form,name=String(input?.value||"").trim(),plan=(this.v0912?.treatment_plans||[]).find(item=>(item.list_as==="task"||item.list_as==="both")&&this.normPlan011(item.name)===this.normPlan011(name));if(!form)return;const hidden=form.elements.planned_treatment_plan_id;if(hidden)hidden.value=plan?String(plan.id):"";if(!plan)return;const title=form.elements.title;if(title)title.value=plan.name;const description=form.elements.description;if(description&&plan.description)description.value=plan.description};
AH012.saveTask=async function(form,values){const result=await AH012Base.saveTask.call(this,form,values),planId=Number(values.planned_treatment_plan_id||0);if(values.task_kind==="treatment"&&planId>0){const tasks=this.findTasks010?this.findTasks010(result):result?.tasks||result?.task?[result.task]:[];for(const task of tasks||[])if(task?.id)await this.ws(`${D}/v0912/task_plan/link`,{task_id:String(task.id),plan_id:planId})}return result};
AH012.form=function(){if(this.modal?.type==="treatment-plan-execute-012")return this.treatmentPlanExecutionForm012();return AH012Base.form.call(this)};
AH012.handleInput=function(event){const input=event.composedPath()[0];if(this.updatePlanDraft012(input))return;if(input?.dataset?.treatmentPlan011!==undefined){const form=input.form,hidden=form?.elements?.planned_treatment_plan_id,plan=(this.v0912?.treatment_plans||[]).find(item=>(item.list_as==="task"||item.list_as==="both")&&this.normPlan011(item.name)===this.normPlan011(input.value));if(hidden)hidden.value=plan?String(plan.id):"";return}return AH012Base.handleInput.call(this,event)};
AH012.handleChange=function(event){const input=event.composedPath()[0],form=input?.form;if(this.updatePlanDraft012(input)){if(input?.dataset?.planComponent012==="type")this.render();return}if(input?.dataset&&"offLabelMed012" in input.dataset){if(this.medBatch0817){this.medBatch0817.showOffLabel=Boolean(input.checked);this.render()}return}if(input?.dataset?.treatmentPlanRun012!==undefined){if(input.value)this.openTreatmentPlanExecution012(Number(input.value),this.medBatch0817?.animalId||this.detail?.animal?.id||"");return}if(input?.dataset?.treatmentPlan011!==undefined){this.applyTreatmentPlan011(input);return}AH012Base.handleChange.call(this,event);if(form?.dataset.form==="task"&&["device_ids","show_off_label","task_kind"].includes(input.name))this.refreshTaskOptions012(form)};
AH012.handleClick=async function(event){const button=event.composedPath().find(node=>node?.dataset?.action),action=button?.dataset?.action;if(action==="plan-component-add-012"){this.ensurePlanDraft012().components.push(this.blankPlanComponent012("medication"));this.render();return}if(action==="plan-component-remove-012"){const index=Number(button.dataset.index),draft=this.ensurePlanDraft012();if(draft.components.length>1&&Number.isInteger(index))draft.components.splice(index,1);else draft.components=[this.blankPlanComponent012("action")];this.render();return}if(action==="delete-treatment-012"){try{await this.ws(`${D}/v0911/treatment/delete`,{treatment_id:Number(button.dataset.id)});await this.loadV0912();this.notify(this.t("treatmentDeleted011"));this.render()}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return}return AH012Base.handleClick.call(this,event)};
AH012.handleSubmit=async function(event){const form=event.composedPath().find(node=>node?.tagName==="FORM");if(!form)return AH012Base.handleSubmit.call(this,event);if(form.dataset.form==="v0912-offlabel"){event.preventDefault();try{const mode=form.elements.mode?.value||"show_all",result=await this.ws(`${D}/v0912/off_label/update`,{mode});this.v0912=this.v0912||{};this.v0912.off_label_mode=result.off_label_mode;this.notify(this.t("offLabelSaved012"));this.render()}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return}if(form.dataset.form==="v0912-treatment"){event.preventDefault();const draft=this.ensurePlanDraft012(),components=draft.components.map(item=>({type:item.type,name:String(item.name||"").trim(),...(item.type==="action"?{}:{dose:Number(item.dose),unit:item.unit||"dose",...(item.route?{route:item.route}:{})}),...(String(item.instructions||"").trim()?{instructions:String(item.instructions).trim()}: {})}));if(!components.length||components.some(item=>!item.name||(item.type!=="action"&&!(item.dose>0)))){this.notify(this.t("noPlanComponents012"),true);return}try{await this.ws(`${D}/v0912/treatment/save`,{name:String(draft.name||"").trim(),species_id:draft.species_id||"",list_as:draft.list_as||"task",description:String(draft.description||"").trim(),components});this.planDraft012=null;await this.loadV0912();this.notify(this.t("treatmentSaved011"));this.render()}catch(error){this.notify(`${this.t("failed")}: ${error?.message||error}`,true)}return}if(form.dataset.form==="treatment-plan-execute-012"){event.preventDefault();const values=data(form),state=this.planExecution012||{};try{this.busy=true;this.render();await this.ws(`${D}/v0912/treatment/execute`,{plan_id:Number(state.planId),animal_id:values.animal_id,occurred_at:`${values.date}T${values.time}`,...(values.notes?{notes:values.notes}:{})});this.planExecution012=null;this.busy=false;await this.after();this.notify(this.t("treatmentPlanExecuted012"))}catch(error){this.busy=false;this.notify(`${this.t("failed")}: ${error?.message||error}`,true);this.render()}return}return AH012Base.handleSubmit.call(this,event)};
AH012.render=function(){AH012Base.render.call(this);const taskForm=this.shadowRoot.querySelector('form[data-form="task"]');if(taskForm)this.refreshTaskOptions012(taskForm);this.shadowRoot.innerHTML+=`<style>.offLabelPolicy012{display:grid;gap:10px;margin-bottom:16px}.offLabelPolicy012 fieldset{display:grid;gap:7px}.offPolicyChoice012{display:flex!important;flex-direction:row!important;align-items:flex-start;gap:8px;padding:7px}.offPolicyChoice012 span{display:flex;flex-direction:column;gap:2px}.offPolicyChoice012 small{color:var(--secondary-text-color)}.medicationExtras012{display:flex;flex-wrap:wrap;gap:10px;align-items:end}.planChooser012{display:flex;flex-direction:column;gap:4px;flex:1;min-width:220px}.offLabelReveal012{display:flex!important;flex-direction:row!important;align-items:center;gap:7px;padding:8px}.treatmentAdminForm012{display:grid;gap:10px}.planTop012{display:grid;grid-template-columns:2fr 1fr 1fr;gap:8px}.planTop012 label,.planDescription012{display:flex;flex-direction:column;gap:3px}.planComponents012{display:grid;gap:9px}.planComponent012{display:grid;gap:7px;padding:10px;border:1px solid var(--divider-color);border-radius:10px;background:var(--secondary-background-color)}.planComponentHead012{display:grid;grid-template-columns:1fr 2fr auto;gap:7px;align-items:end}.planComponentHead012 label,.planDose012 label,.planInstruction012{display:flex;flex-direction:column;gap:3px}.planDose012{display:grid;grid-template-columns:1fr 1fr 1fr;gap:7px}.planInstruction012{grid-column:1/-1}.managedTreatments012>div span{display:flex;flex-direction:column}.treatmentExecHint012,.treatmentExecDescription012{margin:0}.treatmentExecComponents012{display:grid;gap:6px}.treatmentExecComponents012>div{display:grid;grid-template-columns:auto 1fr;gap:8px;align-items:center;padding:8px;border-radius:8px;background:var(--secondary-background-color)}.treatmentExecComponents012 span{display:flex;flex-direction:column}.treatmentExecComponents012 small{color:var(--secondary-text-color)}@media(max-width:720px){.planTop012,.planComponentHead012,.planDose012{grid-template-columns:1fr}.planComponentHead012 button{justify-self:end}.medicationExtras012{display:grid}}</style>`};
