 connectedCallback(){if(!this.eventsBound){this.eventsBound=true;this.shadowRoot.addEventListener("click",e=>void this.handleClick(e));this.shadowRoot.addEventListener("change",e=>this.handleChange(e));this.shadowRoot.addEventListener("input",e=>this.handleInput(e));this.shadowRoot.addEventListener("submit",e=>void this.handleSubmit(e))}this.render();if(this.h&&!this.d)this.load()}
 lang(){return String(this.h?.language||"en").startsWith("de")?0:1}t(k){return T[k]?.[this.lang()]||k}l(v){return L[v]?.[this.lang()]||T[v]?.[this.lang()]||String(v??"–").replaceAll("_"," ")}fmt(v,time=false){if(!v)return"–";const d=new Date(v);return isNaN(d)?esc(v):new Intl.DateTimeFormat(this.lang()?"en-GB":"de-CH",{dateStyle:"medium",...(time?{timeStyle:"short"}:{})}).format(d)}num(v,n=2){return new Intl.NumberFormat(this.lang()?"en-GB":"de-CH",{maximumFractionDigits:n}).format(Number(v))}
 ws(type,p={}){return this.h.callWS({type,...p})}svc(service,p,response=false){return response?this.ws("call_service",{domain:D,service,service_data:p,return_response:true}):this.h.callService(D,service,p)}notify(m,bad=false){this.dispatchEvent(new CustomEvent("hass-notification",{detail:{message:String(m),duration:bad?7000:4000},bubbles:true,composed:true}))}
 async load(){if(!this.h||this.busy)return;this.busy=true;this.render();try{[this.d,this.c]=await Promise.all([this.ws(`${D}/dashboard`),this.c||this.ws(`${D}/catalog`)]);if(this.detail)await this.loadDetail(this.detail.animal.id,false);this.err=null}catch(e){this.err=e?.message||String(e)}this.busy=false;this.render()}
 async loadDetail(id,r=true){try{this.detail=await this.ws(`${D}/animal_detail`,{animal_id:id,event_limit:300});this.view="animal-detail";if(r)this.render()}catch(e){this.notify(`${this.t("failed")}: ${e?.message||e}`,true)}}
 animal(id){return this.d?.animals.find(x=>x.id===id)||this.detail?.animal}occ(id){return this.d?.occurrences.find(x=>x.id===id)||this.detail?.occurrences.find(x=>x.id===id)}task(id){return this.d?.tasks.find(x=>x.id===id)||this.detail?.tasks.find(x=>x.id===id)}
 async handleClick(e){const b=e.composedPath().find(x=>x?.dataset&&(x.dataset.action||x.dataset.view));if(!b)return;const{action,view,id}=b.dataset;if(view){this.view=view;this.filter="";if(view!=="animal-detail")this.detail=null;return this.render()}if(action==="close")return this.open(null);if(action==="refresh")return this.load();if(["create-animal","create-task","record-weight","record-event","record-symptom"].includes(action))return this.open(action,{animalId:id});if(action==="animal-detail")return this.loadDetail(id);if(action==="edit-animal"||action==="animal-status")return this.open(action,{animalId:id});if(action==="execute"||action==="resolve")return this.open(action,{occurrenceId:id,resolution:b.dataset.resolution});try{if(action==="archive"||action==="restore"){const a=this.animal(id);await this.svc(action==="archive"?"archive_animal":"restore_animal",{device_id:a.device_id})}else if(action==="toggle"){const t=this.task(id);await this.svc("set_task_active",{task_id:id,is_active:!t.is_active},true)}else return;await this.after()}catch(x){this.notify(`${this.t("failed")}: ${x?.message||x}`,true)}}
 handleInput(e){const x=e.composedPath().find(y=>y?.dataset?.filter);if(x){this.filter=x.value;this.render();const n=this.shadowRoot.querySelector("[data-filter]");n?.focus();n?.setSelectionRange(n.value.length,n.value.length)}}
 handleChange(e){const x=e.composedPath()[0],f=x?.form;if(!f)return;if(["task_kind","task_scope","planned_vaccination_targets"].includes(x.name))this.syncTask(f);if(["check_result","symptom","vaccination_targets"].includes(x.name))this.syncExec(f)}
 open(type,extra={}){this.modal=type?{type,...extra}:null;this.render()}async after(){this.modal=null;await this.load();this.notify(this.t("done"))}
 async handleSubmit(e){const f=e.composedPath().find(x=>x?.tagName==="FORM");if(!f)return;e.preventDefault();const o=data(f);this.busy=true;this.render();try{if(f.dataset.form==="animal")await this.saveAnimal(o);if(f.dataset.form==="status")await this.saveStatus(o);if(f.dataset.form==="weight")await this.saveWeight(o);if(f.dataset.form==="event")await this.saveEvent(o);if(f.dataset.form==="symptom")await this.saveSymptom(o);if(f.dataset.form==="task")await this.saveTask(f,o);if(f.dataset.form==="execute")await this.saveExecution(f,o);if(f.dataset.form==="resolve")await this.saveResolution(o);this.busy=false;await this.after()}catch(x){this.busy=false;this.notify(`${this.t("failed")}: ${x?.message||x}`,true);this.render()}}
 async saveAnimal(o){if(o.animal_id){const a=this.animal(o.animal_id),p={device_id:a.device_id,name:o.name,species:o.species,breed:o.breed||null,color:o.color||null,birth_date:o.birth_date||null,arrival_date:o.arrival_date||null};if(o.sex)p.sex=o.sex;return this.svc("update_animal",p)}const p={name:o.name,species:o.species};for(const k of["breed","color","sex","birth_date","arrival_date"])if(o[k])p[k]=o[k];return this.svc("create_animal",p)}
 saveStatus(o){return this.svc("set_animal_status",{device_id:this.animal(o.animal_id).device_id,status:o.status})}
 saveWeight(o){const p={device_id:this.animal(o.animal_id).device_id,weight:Number(o.weight),weight_unit:o.weight_unit};for(const k of["occurred_at","notes"])if(o[k])p[k]=o[k];return this.svc("record_weight",p)}
 saveEvent(o){const p={device_id:this.animal(o.animal_id).device_id,event_type:o.event_type,title:o.title};for(const k of["occurred_at","notes"])if(o[k])p[k]=o[k];return this.svc("create_event",p)}
 saveSymptom(o){const p={device_id:this.animal(o.animal_id).device_id,symptom:o.symptom,severity:o.severity};for(const k of["occurred_at","notes"])if(o[k])p[k]=o[k];if(o.symptom==="other")p.custom_symptom=o.custom_symptom;return this.svc("record_symptom",p)}
 async saveTask(f,o){const p={task_scope:o.task_scope,task_kind:o.task_scope==="general"?"reminder":o.task_kind,title:o.title,recurrence_type:o.recurrence_type,recurrence_interval:Number(o.recurrence_interval||1),start_date:o.start_date};for(const k of["description","end_date","due_time"])if(o[k])p[k]=o[k];if(p.task_scope==="animal"){p.device_ids=[...f.querySelectorAll('[name="device_ids"]:checked')].map(x=>x.value);if(!p.device_ids.length)throw Error(this.t("selectOne"))}const m={medication:["planned_medication_name","planned_dose","planned_dose_unit","planned_route"],vaccination:["planned_custom_vaccination_target","planned_vaccine_name","planned_antigen","planned_vaccination_dose","planned_vaccination_dose_unit","planned_vaccination_route"],health_check:["planned_check_focus"],care:["planned_care_action"],veterinary_visit:["planned_visit_reason","planned_provider"]};for(const k of m[p.task_kind]||[])if(o[k])p[k]=k.includes("dose")&&!k.includes("unit")?Number(o[k]):o[k];if(p.task_kind==="vaccination")p.planned_vaccination_targets=[...f.querySelectorAll('[name="planned_vaccination_targets"]:checked')].map(x=>x.value);return this.svc("create_record_task",p,true)}