Object.assign(T,{
 pullToRefresh098:["Zum Aktualisieren nach unten ziehen","Pull down to refresh"],
 releaseToRefresh098:["Loslassen zum Aktualisieren","Release to refresh"],
 refreshing098:["Wird aktualisiert …","Refreshing …"]
});
const AH098=AnimalHealthPanel.prototype;
const AH098Base={body:AH098.body,connectedCallback:AH098.connectedCallback,handleClick:AH098.handleClick,render:AH098.render};
AH098.headerBrand098=function(){return this.brandMarkup0814?this.brandMarkup0814():`<b class="brand"><ha-icon icon="mdi:paw"></ha-icon><span>Animal Health</span></b>`};
AH098.headerNav098=function(){const items=[["overview","mdi:view-dashboard"],["timeline","mdi:timeline-clock"],["settings081","mdi:cog-outline"]];return items.map(([view,icon])=>{const active=this.view===view||(view==="settings081"&&["groups081","group-detail"].includes(this.view));return`<button data-view="${view}" class="${active?"on":""}" title="${esc(this.t(view))}" aria-label="${esc(this.t(view))}"><ha-icon icon="${icon}"></ha-icon><span>${this.t(view)}</span></button>`}).join("")};
AH098.pullIndicator098=function(){const refreshing=Boolean(this.pullRefreshing098),label=this.t(refreshing?"refreshing098":"pullToRefresh098");return`<div class="pullRefresh098 ${refreshing?"refreshing098":""}" role="status" aria-live="polite"><ha-icon icon="mdi:refresh"></ha-icon><span>${label}</span></div>`};
AH098.body=function(){if(!this.d)return AH098Base.body.call(this);return`${this.d.version!==V?`<div class="warn">${this.t("version")}</div>`:""}<header><button class="menuButton" data-action="menu" aria-label="Menu"><ha-icon icon="mdi:menu"></ha-icon></button>${this.headerBrand098()}<nav>${this.headerNav098()}</nav></header>${this.pullIndicator098()}<main>${this.page()}</main>${this.modalHtml()}`};
AH098.scrollTop098=function(){let node=this,seen=new Set();while(node&&!seen.has(node)){seen.add(node);if(node!==this&&typeof node.scrollTop==="number"&&node.scrollTop>0)return node.scrollTop;const root=node.getRootNode?.();node=node.parentElement||root?.host||null}const doc=globalThis.document;return Math.max(0,Number(globalThis.scrollY||doc?.scrollingElement?.scrollTop||doc?.documentElement?.scrollTop||0))};
AH098.pullElement098=function(){return this.shadowRoot?.querySelector?.(".pullRefresh098")||null};
AH098.pullReset098=function(){this.pullStartY098=null;this.pullStartX098=null;this.pullDistance098=0;const indicator=this.pullElement098();if(!indicator)return;indicator.classList.remove("dragging098","ready098");indicator.style.removeProperty("transform");indicator.style.removeProperty("opacity");const icon=indicator.querySelector?.("ha-icon");if(icon)icon.style.removeProperty("transform");const label=indicator.querySelector?.("span");if(label)label.textContent=this.t("pullToRefresh098")};
AH098.pullStart098=function(event){if(this.busy||this.pullRefreshing098||this.modal||event.touches?.length!==1||this.scrollTop098()>0){this.pullReset098();return}this.pullStartY098=event.touches[0].clientY;this.pullStartX098=event.touches[0].clientX;this.pullDistance098=0};
AH098.pullMove098=function(event){if(this.pullStartY098==null||event.touches?.length!==1)return;const dy=event.touches[0].clientY-this.pullStartY098,dx=event.touches[0].clientX-this.pullStartX098;if(dy<=0||this.scrollTop098()>0||Math.abs(dx)>dy){this.pullReset098();return}if(dy>5)event.preventDefault();this.pullDistance098=dy;const offset=Math.min(78,dy*.7),indicator=this.pullElement098();if(!indicator)return;indicator.classList.add("dragging098");indicator.classList.toggle("ready098",dy>=84);indicator.style.transform=`translate(-50%,${offset-58}px)`;indicator.style.opacity=String(Math.min(1,offset/38));const icon=indicator.querySelector?.("ha-icon");if(icon)icon.style.transform=`rotate(${Math.min(270,dy*2.5)}deg)`;const label=indicator.querySelector?.("span");if(label)label.textContent=this.t(dy>=84?"releaseToRefresh098":"pullToRefresh098")};
AH098.refreshFromPull098=async function(){if(this.busy||this.pullRefreshing098)return;this.pullRefreshing098=true;this.render();try{await this.load()}finally{this.pullRefreshing098=false;this.render()}};
AH098.pullEnd098=function(){const ready=Number(this.pullDistance098||0)>=84;this.pullReset098();if(ready)void this.refreshFromPull098()};
AH098.connectedCallback=function(){AH098Base.connectedCallback.call(this);if(this.pullRefreshBound098)return;this.pullRefreshBound098=true;this.shadowRoot.addEventListener("touchstart",event=>this.pullStart098(event),{passive:true});this.shadowRoot.addEventListener("touchmove",event=>this.pullMove098(event),{passive:false});this.shadowRoot.addEventListener("touchend",()=>this.pullEnd098(),{passive:true});this.shadowRoot.addEventListener("touchcancel",()=>this.pullReset098(),{passive:true})};
AH098.handleClick=async function(event){const button=event.composedPath().find(node=>node?.dataset?.action),action=button?.dataset?.action,id=String(button?.dataset?.id||"");if(action==="home-open-group-091"){this.filter="";this.detail=null;if(id&&id!=="ungrouped"){this.groupDetailId=id;this.view="group-detail"}else{this.groupFilter="ungrouped";this.tagFilter="all";this.view="animals"}this.render();return}return AH098Base.handleClick.call(this,event)};
AH098.render=function(){AH098Base.render.call(this);this.shadowRoot.innerHTML+=`<style>.pullRefresh098{position:fixed;z-index:20;top:68px;left:50%;display:flex;align-items:center;gap:7px;max-width:calc(100vw - 32px);padding:8px 12px;border:1px solid var(--divider-color);border-radius:999px;background:var(--card-background-color);box-shadow:var(--ha-card-box-shadow,0 3px 12px #0003);color:var(--secondary-text-color);opacity:0;transform:translate(-50%,-58px);pointer-events:none;transition:transform .2s ease,opacity .2s ease}.pullRefresh098.dragging098{transition:none}.pullRefresh098.ready098{color:var(--primary-color);border-color:var(--primary-color)}.pullRefresh098.refreshing098{opacity:1;transform:translate(-50%,8px);color:var(--primary-color)}.pullRefresh098.refreshing098 ha-icon{animation:pullSpin098 .8s linear infinite}.pullRefresh098 span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@keyframes pullSpin098{to{transform:rotate(360deg)}}@media(pointer:fine){.pullRefresh098{display:none}}</style>`};
