AH026.attachmentsForEvent026=function(event){const id=String(event?.id||"");return(this.detail?.attachments||[]).filter(item=>String(item.event_id||"")===id)};
AH026.attachmentStrip026=function(event,expanded=false){const items=this.attachmentsForEvent026(event);if(!items.length)return"";return`<div class="timelineAttachments026 ${expanded?"expanded026":"compact026"}" aria-label="${esc(this.t("attachments026"))}">${items.map(item=>{const image=String(item.media_type||"").startsWith("image/"),url=this.attachmentUrls024?.[item.id]?.thumbnail;if(image)return`<button type="button" class="timelineImage026" data-action="attachment-preview-024" data-id="${esc(item.id)}" title="${esc(item.title||item.filename||this.t("imagePreview024"))}">${url?`<img src="${esc(url)}" alt="">`:`<ha-icon icon="mdi:file-image-outline"></ha-icon>`}</button>`;return`<button type="button" class="timelineFile026" data-action="download-attachment" data-id="${esc(item.id)}" title="${esc(item.title||item.filename||"")}"><ha-icon icon="mdi:file-document-outline"></ha-icon><span>${esc(item.title||item.filename||"")}</span></button>`}).join("")}</div>`};
AH026.treatmentBundle021=function(event){let html=AH026Base.treatmentBundle021.call(this,event),expanded=this.expandedTreatmentSet021?.().has(String(event?.id||"")),strip=this.attachmentStrip026(event,Boolean(expanded)),badge=this.scopeBadge026(event);if(badge&&!html.includes("scopeBadge026"))html=html.replace(/(<div class="bundleText021"><b>[\s\S]*?<\/b>)/,`$1<small class="scopeBadge026">${esc(badge)}</small>`);if(strip){if(expanded&&html.includes('<div class="bundleChildren021">'))html=html.replace('<div class="bundleChildren021">',`<div class="bundleChildren021">${strip}`);else html=html.replace(/(<\/div><button type="button" class="bundleChevron021")/,`${strip}$1`)}return html};
AH026.eventCompact0817=function(event){let html=AH026Base.eventCompact0817.call(this,event),badge=this.scopeBadge026(event);if(badge&&html&&!html.includes("scopeBadge026"))html=html.replace(/(<b>[\s\S]*?<\/b>)/,`$1<small class="scopeBadge026">${esc(badge)}</small>`);return html};
AH026.taskCompact=function(task){if(typeof AH026Base.taskCompact!=="function")return"";let html=AH026Base.taskCompact.call(this,task),badge=this.scopeBadge026(task);if(badge&&html&&!html.includes("scopeBadge026"))html=html.replace(/(<b>[\s\S]*?<\/b>)/,`$1<small class="scopeBadge026">${esc(badge)}</small>`);return html};
AH026.taskManagementRow097=function(task){if(typeof AH026Base.taskManagementRow097!=="function")return"";let html=AH026Base.taskManagementRow097.call(this,task),badge=this.scopeBadge026(task);if(badge&&html&&!html.includes("scopeBadge026"))html=html.replace(/(<b>[\s\S]*?<\/b>)/,`$1<small class="scopeBadge026">${esc(badge)}</small>`);return html};

AH026.fileFields=function(){let html=AH026Base.fileFields.call(this);html=html.replace('<input type="file" data-attachment-input024 multiple','<input type="file" name="attachment_files" data-attachment-input024 multiple="multiple"');return html};
AH026.captureFiles026=function(form){return[...(this.filesFrom?.(form)||[])];};
AH026.uploadFileSet026=async function(files,form,animalId,eventId=null){if(!files?.length)return[];const max=this.features?.max_attachment_size_bytes||15728640,title=form?.elements?.document_title?.value||null,uploaded=[];for(const file of files){if(file.size>max)throw Error(this.t("fileTooLarge"));const target=await this.ws(`${D}/attachments/upload`,{animal_id:animalId,...(eventId?{event_id:eventId}:{})}),payload=new FormData();payload.append("file",file,file.name||"document.jpg");if(title)payload.append("title",title);const response=await fetch(target.url,{method:"POST",body:payload,credentials:"same-origin"});if(!response.ok)throw Error((await response.text())||`HTTP ${response.status}`);uploaded.push(await response.json())}return uploaded};
AH026.uploadFilesToTargets026=async function(files,form,events){if(!files?.length||!events?.length)return;const byAnimal=new Map;for(const event of events){const animalId=String(event?.animal_id||"");if(!animalId||byAnimal.has(animalId))continue;const role=String(event?.data?.treatment_execution_role||"");if(event.event_type==="treatment"&&role&&role!=="parent")continue;byAnimal.set(animalId,event)}if(!byAnimal.size){for(const event of events){const animalId=String(event?.animal_id||"");if(animalId&&!byAnimal.has(animalId))byAnimal.set(animalId,event)}}for(const[animalId,event]of byAnimal)await this.uploadFileSet026(files,form,animalId,event.id);this.clearAttachmentDraft024?.()};

AH026.handleInput=function(event){const input=event.composedPath()[0];if(input?.type==="file"&&input?.dataset&&"attachmentInput024" in input.dataset){const files=[...input.files||[]];if(files.length){this.addAttachmentFiles024?.(files);input.value="";this.refreshAttachmentDraft024?.(input.form)}return}return AH026Base.handleInput.call(this,event)};
AH026.handleChange=function(event){const input=event.composedPath()[0];if(input?.type==="file"&&input?.dataset&&"attachmentInput024" in input.dataset){const files=[...input.files||[]];if(files.length){this.addAttachmentFiles024?.(files);input.value="";this.refreshAttachmentDraft024?.(input.form)}return}if(input?.dataset&&"targetGroup026" in input.dataset){const key=input.dataset.key,state=this._targetStates026?.[key];if(state){state.groupId=String(input.value||"");this.updateTargetCompatibility026(input.closest("[data-target-selector026]"),state)}return}if(input?.dataset&&"targetAnimal026" in input.dataset){const key=input.dataset.key,state=this._targetStates026?.[key];if(state){const value=String(input.value||""),ids=new Set((state.animalIds||[]).map(String));input.checked?ids.add(value):ids.delete(value);state.animalIds=[...ids];this.updateTargetCompatibility026(input.closest("[data-target-selector026]"),state)}return}return AH026Base.handleChange.call(this,event)};
AH026.handleClick=async function(event){const button=event.composedPath().find(node=>node?.dataset?.action),action=button?.dataset?.action;if(action==="target-scope-026"){const key=button.dataset.key,state=this._targetStates026?.[key],wrapper=button.closest("[data-target-selector026]");if(!state||!wrapper)return;state.scope=button.dataset.scope||"animals";if(state.scope==="group"&&!state.groupId)state.groupId=String(this.targetGroups026()[0]?.id||"");for(const item of wrapper.querySelectorAll('[data-action="target-scope-026"]')){const active=item.dataset.scope===state.scope;item.classList.toggle("active026",active);item.setAttribute("aria-pressed",active?"true":"false")}for(const panel of wrapper.querySelectorAll("[data-target-panel026]"))panel.hidden=panel.dataset.targetPanel026!==state.scope;this.updateTargetCompatibility026(wrapper,state);if(key==="task")this.syncTask?.(button.closest("form"));return}if(action==="plan-component-up-026"||action==="plan-component-down-026"){const draft=this.ensurePlanDraft012(),index=Number(button.dataset.index),delta=action==="plan-component-up-026"?-1:1,target=index+delta;if(!draft?.components||target<0||target>=draft.components.length)return;[draft.components[index],draft.components[target]]=[draft.components[target],draft.components[index]];this.render();return}return AH026Base.handleClick.call(this,event)};

